/* GENERATED by tools/stamp-assets.mjs — do not edit; rerun it.
   Data file -> first 8 hex of its SHA-256, so fetches of ssb/** are
   cache-busted the same way the module graph is (docs/ssb.md 7.2). */
export const STAMPS = {
    "ssb/content/ethmoid-frontal-orbit.json": "d721cb0a",
    "ssb/content/nasal-maxillary-ppf.json": "59ee5154",
    "ssb/content/pathology-inflammatory.json": "eee42381",
    "ssb/content/pathology-neoplastic.json": "781d9627",
    "ssb/content/sources.json": "80a8ba0b",
    "ssb/content/sphenoid-sellar-clival.json": "14bd5e74",
    "ssb/geometry/labels.json": "d094c3d6",
    "ssb/geometry/landmarks.json": "17ffee13",
    "ssb/geometry/landmarks.meta.json": "0741b285",
    "ssb/geometry/sweeps.json": "61157fed",
    "ssb/geometry/sweeps.meta.json": "99680500",
    "ssb/models/core.glb.gz": "1835a061",
    "ssb/models/ethmoid-frontal.glb.gz": "e88ed358",
    "ssb/models/packs.json": "f4912b54",
    "ssb/models/sphenoid-sellar.glb.gz": "a8fc1fc8",
    "ssb/models/walls.glb.gz": "cd3b3259",
    "ssb/ct/ct.json": "74fa6819",
    "ssb/ct/ct.u8.gz": "1fc8bb84",
    "ssb/ct/labels.u16.gz": "ba676f07",
    "ssb/ct/sdf-s.anterior-cranial-fossa.u8.gz": "71b9afb7",
    "ssb/ct/sdf-s.anterior-ethmoidal-artery.u8.gz": "1e15470e",
    "ssb/ct/sdf-s.internal-carotid-artery.u8.gz": "4d93aa9d",
    "ssb/ct/sdf-s.optic-nerve.u8.gz": "c31dd83c",
    "ssb/ct/sdf-s.orbit.u8.gz": "498815f3",
};
