/* GENERATED by tools/stamp-assets.mjs — do not edit; rerun it.
   Data file -> first 8 hex of its SHA-256, so fetches of ssb/** are
   cache-busted the same way the module graph is (docs/ssb.md 7.2). */
export const STAMPS = {
    "ssb/content/ethmoid-frontal-orbit.json": "2e2be034",
    "ssb/content/nasal-maxillary-ppf.json": "9b471526",
    "ssb/content/pathology-inflammatory.json": "eee42381",
    "ssb/content/pathology-neoplastic.json": "781d9627",
    "ssb/content/sources.json": "80a8ba0b",
    "ssb/content/sphenoid-sellar-clival.json": "14bd5e74",
};
