#!/usr/bin/env node
/* =============================================================
   stamp-assets.mjs — cache-busting for same-origin CSS/JS.

   GitHub Pages (and its CDN) cache every file for ~10 minutes, each
   URL on its own clock. Right after a deploy a browser can pair the
   new HTML with the old stylesheet — the 2026-09 redesign showed up
   on phones as new markup under the pre-redesign css/onepager.css.
   Stamping each reference with a hash of the file's bytes
   (`css/site.css?v=1a2b3c4d`) makes every changed file a URL no
   cache has seen, so HTML and assets always arrive as one release.

   Not a build step: it rewrites the committed HTML in place, and the
   stamps are committed. `tools/check-data.mjs` fails on a stale or
   missing stamp, so an edited CSS/JS file cannot ship unstamped.

   Covers <link href> and <script src> pointing into css/ or js/ in
   every root *.html. Fonts, images and the module files that
   js/oksat-viewer.js injects at runtime are not stamped.

   SSB's ES-module graph (js/ssb, docs/ssb.md section 7.2) needs more
   than the HTML pass: main.js?v=... imports ./scene.js, which the CDN
   caches on its own clock. So this tool also
     1. regenerates js/ssb/stamps.js (data file -> hash, for fetch URLs)
        from every file under ssb/content, ssb/geometry, ssb/models, ssb/ct, ssb/states;
     2. topologically sorts the .js files under js/ssb by relative static and dynamic
        imports and rewrites each specifier to ./x.js?v=<hash of x>
        leaves-first, so a changed leaf re-stamps every importer up to the
        HTML. An import cycle is an error. Imports into
        js/vendor/three-<version>/ stay unstamped (the versioned directory
        is the cache key, and one URL per file keeps one module instance).
   Import specifiers in js/ssb must be string literals; bare specifiers are
   errors (there is no import map — it would be an inline script).

   Usage:  node tools/stamp-assets.mjs           # rewrite stale stamps
           node tools/stamp-assets.mjs --check   # report only; exit 1 if stale

   Pure Node, zero dependencies.
   ============================================================= */
import crypto from 'crypto';
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');

/* <link … href="css/x.css[?v=…]"> and <script … src="js/x.js[?v=…]">.
   Groups: 1 = tag up to the opening quote, 2 = path, 3 = old query. */
const REF = /(<(?:link|script)\b[^>]*?\b(?:href|src)=")((?:css|js)\/[^"?#]+\.(?:css|js))(\?[^"]*)?"/g;

export function hashOf(file) {
  return crypto.createHash('sha256').update(fs.readFileSync(path.join(ROOT, file))).digest('hex').slice(0, 8);
}

/* Returns { html, stale } — html with every reference stamped, and the
   references whose stamp was missing or wrong. A missing file is left
   as-is (check-data.mjs reports it separately). */
export function stampHtml(html) {
  const stale = [];
  const out = html.replace(REF, (whole, head, file, query) => {
    if (!fs.existsSync(path.join(ROOT, file))) return whole;
    const want = '?v=' + hashOf(file);
    if (query !== want) stale.push(`${file}${query || ''} -> ${file}${want}`);
    return `${head}${file}${want}"`;
  });
  return { html: out, stale };
}

/* ---------------- SSB module graph (docs/ssb.md 7.2) ---------------- */

const SSB_MODULE_DIR = 'js/ssb';
const SSB_STAMPS_FILE = 'js/ssb/stamps.js';
const SSB_DATA_DIRS = ['ssb/content', 'ssb/geometry', 'ssb/models', 'ssb/ct', 'ssb/states'];
const SSB_VENDOR = /^js\/vendor\/three-[^/]+\//;

/* Every import/export-from/dynamic-import with a string-literal specifier.
   Groups: 1 = the statement head, 2 = quote, 3 = specifier.
   `[^'";]*?` lets a multi-line `import { a,\n b } from '…'` match without
   ever running past a string or a statement end. */
const SPEC = /(\b(?:import|export)\b[^'";]*?\bfrom\s*|\bimport\s*\(\s*|\bimport\s+)(['"])([^'"\n]+)\2/g;

function sha8(data) {
  return crypto.createHash('sha256').update(data).digest('hex').slice(0, 8);
}

function walk(dirRel) {
  const abs = path.join(ROOT, dirRel);
  if (!fs.existsSync(abs)) return [];
  const out = [];
  for (const ent of fs.readdirSync(abs, { withFileTypes: true }).sort((a, b) => (a.name < b.name ? -1 : 1))) {
    if (ent.name.startsWith('.')) continue;
    const rel = `${dirRel}/${ent.name}`;
    if (ent.isDirectory()) out.push(...walk(rel));
    else if (ent.isFile()) out.push(rel);
  }
  return out;
}

/* The text js/ssb/stamps.js must have for the data files on disk now. */
export function ssbStampsSource() {
  const map = {};
  for (const dir of SSB_DATA_DIRS) for (const f of walk(dir)) map[f] = hashOf(f);
  const rows = Object.keys(map).map((k) => `    ${JSON.stringify(k)}: ${JSON.stringify(map[k])},\n`).join('');
  return `/* GENERATED by tools/stamp-assets.mjs — do not edit; rerun it.
   Data file -> first 8 hex of its SHA-256, so fetches of ssb/** are
   cache-busted the same way the module graph is (docs/ssb.md 7.2). */
export const STAMPS = {${rows ? '\n' + rows : ''}};
`;
}

/* Stamp js/ssb. Returns { stale, errors }; with { write: true } the stale
   files are rewritten (nothing is written if there are errors). Never
   changes anything outside js/ssb. */
export function stampSsb({ write = false } = {}) {
  const stale = [];
  const errors = [];
  const dirAbs = path.join(ROOT, SSB_MODULE_DIR);
  if (!fs.existsSync(dirAbs)) return { stale, errors };

  /* Virtual file contents: what each module must contain. */
  const disk = {};
  const want = {};
  for (const f of walk(SSB_MODULE_DIR).filter((x) => x.endsWith('.js'))) {
    disk[f] = fs.readFileSync(path.join(ROOT, f), 'utf8');
    want[f] = disk[f];
  }
  const stampsSrc = ssbStampsSource();
  if (disk[SSB_STAMPS_FILE] !== stampsSrc) stale.push(`${SSB_STAMPS_FILE} (data hashes changed)`);
  want[SSB_STAMPS_FILE] = stampsSrc;

  /* Dependency edges (only into js/ssb; vendor imports are validated, not stamped). */
  const deps = {};
  const classify = (from, spec) => {
    if (!/^\.{1,2}\//.test(spec)) return { error: `${from}: non-relative import '${spec}' (no import map exists; use a relative path)` };
    const bare = spec.replace(/[?#].*$/, '');
    const target = path.posix.normalize(path.posix.join(path.posix.dirname(from), bare));
    if (SSB_VENDOR.test(target)) {
      return fs.existsSync(path.join(ROOT, target)) ? { vendor: target } : { error: `${from}: imports missing file ${target}` };
    }
    if (target in want) return { module: target, bare };
    return { error: `${from}: import '${spec}' resolves to ${target}, which is neither a js/ssb module nor js/vendor/three-*/` };
  };
  for (const f of Object.keys(want)) {
    deps[f] = [];
    for (const m of want[f].matchAll(SPEC)) {
      const c = classify(f, m[3]);
      if (c.error) errors.push(c.error);
      else if (c.module) deps[f].push(c.module);
    }
  }

  /* Leaves-first order; a back edge is an import cycle. */
  const order = [];
  const state = {};
  const stack = [];
  const visit = (f) => {
    if (state[f] === 2) return;
    if (state[f] === 1) {
      errors.push(`import cycle: ${[...stack.slice(stack.indexOf(f)), f].join(' -> ')}`);
      return;
    }
    state[f] = 1; stack.push(f);
    for (const d of deps[f]) visit(d);
    stack.pop(); state[f] = 2;
    order.push(f);
  };
  for (const f of Object.keys(want).sort()) visit(f);
  if (errors.length) return { stale, errors };

  /* Rewrite each module's specifiers to the final hash of its targets. */
  const hash = {};
  for (const f of order) {
    const changes = [];
    want[f] = want[f].replace(SPEC, (whole, head, q, spec) => {
      const c = classify(f, spec);
      if (!c.module) return whole;
      const next = `${c.bare}?v=${hash[c.module]}`;
      if (next !== spec) changes.push(`${spec} -> ${next}`);
      return `${head}${q}${next}${q}`;
    });
    hash[f] = sha8(want[f]);
    if (changes.length) stale.push(`${f}: ${changes.join(', ')}`);
  }

  if (write) {
    for (const f of Object.keys(want)) {
      if (want[f] !== disk[f]) fs.writeFileSync(path.join(ROOT, f), want[f]);
    }
  }
  return { stale, errors };
}

export function rootPages() {
  return fs.readdirSync(ROOT).filter((f) => f.endsWith('.html')).sort();
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  const check = process.argv.includes('--check');
  let staleCount = 0;
  /* SSB first: ssb.html's stamp on js/ssb/main.js hashes the *rewritten* file. */
  const ssb = stampSsb({ write: !check });
  for (const e of ssb.errors) console.log(`error   ${e}`);
  for (const s of ssb.stale) console.log(`${check ? 'stale ' : 'stamped'}  ${s}`);
  staleCount += ssb.stale.length;
  if (ssb.errors.length) process.exit(1);
  for (const page of rootPages()) {
    const abs = path.join(ROOT, page);
    const { html, stale } = stampHtml(fs.readFileSync(abs, 'utf8'));
    staleCount += stale.length;
    for (const s of stale) console.log(`${check ? 'stale ' : 'stamped'}  ${page}: ${s}`);
    if (!check && stale.length) fs.writeFileSync(abs, html);
  }
  if (!staleCount) console.log('all asset stamps current');
  process.exit(check && staleCount ? 1 : 0);
}
