// ─────────────────────────────────────────────────────────────────────
// MODULE · Pediatric Hearing Loss
// Schema: { meta, DOMAINS, CONCEPTS, ITEMS }
// Consumed by StudyViewer — engine reads everything from this object.
// ─────────────────────────────────────────────────────────────────────

const meta = {
  id: 'pediatrics',
  title: 'Pediatric\nHearing Loss',
  subtitle:
    'Forty MCQs traversing embryology, conductive and sensorineural causes, syndromic genetics, screening, and clinical cases. Answers reveal mechanism; concept tags link to related questions.',
  kicker: 'MCQ · Pediatric Module',
};

const DOMAINS = {
  foundations: { label: 'Foundations', color: '#8B6F47', hex: 'rgba(139,111,71,0.12)' },
  CHL: { label: 'Conductive', color: '#7B6B85', hex: 'rgba(123,107,133,0.14)' },
  SNHL: { label: 'Sensorineural', color: '#A0635E', hex: 'rgba(160,99,94,0.14)' },
  syndromic: { label: 'Syndromic', color: '#2C5454', hex: 'rgba(44,84,84,0.14)' },
  workup: { label: 'Workup', color: '#7B7B4A', hex: 'rgba(123,123,74,0.14)' },
  management: { label: 'Management', color: '#5C4F7B', hex: 'rgba(92,79,123,0.14)' },
  cases: { label: 'Cases', color: '#8B4513', hex: 'rgba(139,69,19,0.14)' },
};

const CONCEPTS = {
  embryology: { label: 'Embryology', domain: 'foundations' },
  'external-ear': { label: 'External Ear', domain: 'foundations' },
  'middle-ear': { label: 'Middle Ear', domain: 'foundations' },
  'inner-ear': { label: 'Inner Ear', domain: 'foundations' },
  ossicles: { label: 'Ossicles', domain: 'foundations' },
  EAC: { label: 'EAC', domain: 'foundations' },
  'first-arch': { label: 'First Arch', domain: 'foundations' },
  physiology: { label: 'Physiology', domain: 'foundations' },
  tonotopy: { label: 'Tonotopy', domain: 'foundations' },
  NIHL: { label: 'Noise-Induced HL', domain: 'foundations' },
  mechanism: { label: 'Mechanism', domain: 'foundations' },
  potassium: { label: 'K⁺ Recycling', domain: 'foundations' },
  collagen: { label: 'Collagen', domain: 'foundations' },
  vestibular: { label: 'Vestibular', domain: 'foundations' },
  epidemiology: { label: 'Epidemiology', domain: 'foundations' },
  CHL: { label: 'Conductive HL', domain: 'CHL' },
  atresia: { label: 'Aural Atresia', domain: 'CHL' },
  jahrsdoerfer: { label: 'Jahrsdoerfer', domain: 'CHL' },
  BCD: { label: 'BCDs / BAHA', domain: 'CHL' },
  cholesteatoma: { label: 'Cholesteatoma', domain: 'CHL' },
  congenital: { label: 'Congenital Anomalies', domain: 'CHL' },
  'acquired-SNHL': { label: 'Acquired SNHL', domain: 'SNHL' },
  cCMV: { label: 'Congenital CMV', domain: 'SNHL' },
  ototoxicity: { label: 'Ototoxicity', domain: 'SNHL' },
  mitochondrial: { label: 'Mitochondrial', domain: 'SNHL' },
  'genetic-SNHL': { label: 'Genetic SNHL', domain: 'SNHL' },
  GJB2: { label: 'GJB2 / Cx26', domain: 'SNHL' },
  meningitis: { label: 'Meningitis', domain: 'SNHL' },
  'syndromic-AD': { label: 'Syndromic (AD)', domain: 'syndromic' },
  'syndromic-AR': { label: 'Syndromic (AR)', domain: 'syndromic' },
  'syndromic-XL': { label: 'Syndromic (X-linked)', domain: 'syndromic' },
  BOR: { label: 'BOR', domain: 'syndromic' },
  'treacher-collins': { label: 'Treacher Collins', domain: 'syndromic' },
  waardenburg: { label: 'Waardenburg', domain: 'syndromic' },
  CHARGE: { label: 'CHARGE', domain: 'syndromic' },
  pendred: { label: 'Pendred', domain: 'syndromic' },
  EVA: { label: 'EVA', domain: 'syndromic' },
  usher: { label: 'Usher', domain: 'syndromic' },
  DFN3: { label: 'DFN3 / Phelps', domain: 'syndromic' },
  alport: { label: 'Alport', domain: 'syndromic' },
  JLN: { label: 'Jervell & Lange-Nielsen', domain: 'syndromic' },
  audiology: { label: 'Audiology', domain: 'workup' },
  ANSD: { label: 'Auditory Neuropathy', domain: 'workup' },
  imaging: { label: 'Imaging', domain: 'workup' },
  diagnosis: { label: 'Diagnosis', domain: 'workup' },
  workup: { label: 'Workup', domain: 'workup' },
  EHDI: { label: 'EHDI', domain: 'workup' },
  screening: { label: 'Screening', domain: 'workup' },
  surgical: { label: 'Surgical', domain: 'management' },
  treatment: { label: 'Treatment', domain: 'management' },
  CI: { label: 'Cochlear Implant', domain: 'management' },
  emerging: { label: 'Emerging Therapy', domain: 'management' },
  'gene-therapy': { label: 'Gene Therapy', domain: 'management' },
  cases: { label: 'Clinical Cases', domain: 'cases' },
};

const ITEMS = [
  {
    id: 'q1',
    type: 'mcq',
    stem: 'During which embryonic weeks do the six Hillocks of His form?',
    options: [
      { id: 'a', text: 'Weeks 3–4' },
      { id: 'b', text: 'Weeks 5–6' },
      { id: 'c', text: 'Weeks 8–9' },
      { id: 'd', text: 'Weeks 12–14' },
    ],
    correct: 'b',
    brief: 'Hillocks of His form during weeks 5–6 from mesoderm of the first and second pharyngeal arches.',
    detailed: 'The pinna develops from six mesodermal prominences (hillocks) during weeks 5–6. Hillocks 1–3 derive from the first (mandibular) arch and form the tragus, helix root (crus), and helix proper. Hillocks 4–6 derive from the second (hyoid) arch and form the antihelix, antitragus, and lobule/inferior helix. First-arch syndromes (Treacher Collins, Goldenhar, Crouzon) preferentially affect 1–3 derivatives.',
    concepts: ['embryology', 'external-ear', 'first-arch'],
  },
  {
    id: 'q2',
    type: 'mcq',
    stem: 'Which adult auricular structure derives from the third Hillock of His?',
    options: [
      { id: 'a', text: 'Tragus' },
      { id: 'b', text: 'Antihelix' },
      { id: 'c', text: 'Helix' },
      { id: 'd', text: 'Lobule' },
    ],
    correct: 'c',
    brief: 'Hillock 3 (first arch) forms the helix proper.',
    detailed: 'Memorize: 1 = tragus, 2 = helix crus/root, 3 = helix, 4 = antihelix, 5 = antitragus, 6 = lobule and inferior helix. Hillocks 1–3 are first-arch derivatives; 4–6 are second-arch. Microtia grading correlates with the extent of hillock failure; Grade III microtia ("peanut ear") reflects near-total failure across all six.',
    concepts: ['embryology', 'external-ear', 'first-arch'],
  },
  {
    id: 'q3',
    type: 'mcq',
    stem: 'Failure of meatal plug resorption by the 21st fetal week most directly results in:',
    options: [
      { id: 'a', text: 'Microtia' },
      { id: 'b', text: 'EAC atresia or stenosis' },
      { id: 'c', text: 'Tympanic membrane perforation' },
      { id: 'd', text: 'Ossicular discontinuity' },
    ],
    correct: 'b',
    brief: 'The meatal plug, formed at week 9, must resorb by week 21 to canalize the EAC.',
    detailed: 'The first pharyngeal groove invaginates to form the primary meatus, which fills with proliferating ectodermal cells (meatal plug) at 9 weeks. The plug expands into the disc-shaped meatal plate, contacts the malleus, and thins to form the outer epithelial layer of the TM. If the core fails to canalize by 21 weeks, congenital aural atresia or stenosis results — often unilateral, right-sided, and male-predominant. Microtia is a hillock-formation failure; TM perforation is acquired.',
    concepts: ['embryology', 'external-ear', 'EAC', 'atresia'],
  },
  {
    id: 'q4',
    type: 'mcq',
    stem: 'The head of the malleus and body of the incus derive from:',
    options: [
      { id: 'a', text: 'First pharyngeal pouch endoderm' },
      { id: 'b', text: "Meckel's (first arch) cartilage" },
      { id: 'c', text: "Reichert's (second arch) cartilage" },
      { id: 'd', text: 'Otic capsule mesoderm' },
    ],
    correct: 'b',
    brief: "Meckel's (1st arch) cartilage forms the head of malleus and body and short process of incus.",
    detailed: "First arch (Meckel's): head of malleus, body and short process of incus. Second arch (Reichert's): manubrium of malleus, long process and body of incus, stapes superstructure, tympanic surface of stapes footplate. The vestibular surface of the stapes footplate derives from the otic capsule. The incudostapedial joint forms at 8.5 weeks; cartilaginous ossicular skeleton replaces mesenchymal precursors at 15 weeks.",
    concepts: ['embryology', 'middle-ear', 'ossicles', 'first-arch'],
  },
  {
    id: 'q5',
    type: 'mcq',
    stem: 'When does the otic capsule complete ossification?',
    options: [
      { id: 'a', text: 'Week 8' },
      { id: 'b', text: 'Week 12' },
      { id: 'c', text: 'Week 16' },
      { id: 'd', text: 'Week 21' },
    ],
    correct: 'c',
    brief: 'The otic capsule ossifies at week 16 of fetal development.',
    detailed: 'Mesenchyme encapsulates the otocyst and forms the cartilaginous otic capsule, which ossifies at 16 weeks. The membranous labyrinth begins forming at week 3 from ectodermal thickening (otic placode → otic cyst at week 4). The cochlear aqueduct contains the periotic duct and communicates the subarachnoid space with the base of the scala tympani — explaining why perilymph and CSF share similar electrolyte composition.',
    concepts: ['embryology', 'inner-ear'],
  },
  {
    id: 'q6',
    type: 'mcq',
    stem: 'The middle ear transformer ratio of approximately 22:1 produces what gain?',
    options: [
      { id: 'a', text: '5–10 dB' },
      { id: 'b', text: '15–20 dB' },
      { id: 'c', text: '25–30 dB' },
      { id: 'd', text: '40–50 dB' },
    ],
    correct: 'c',
    brief: 'Areal ratio (17:1) × lever ratio (1.3:1) ≈ 22:1, producing ~25–30 dB of gain.',
    detailed: 'Two mechanisms compensate for the air–fluid impedance mismatch: (1) the areal ratio between the 55 mm² pars tensa and 3.2 mm² stapes footplate concentrates sound energy 17×, and (2) the malleus handle (9 mm) acting on the incus long process (7 mm) creates a 1.3:1 lever advantage. Complete ossicular discontinuity can produce ~60 dB CHL when phase cancellation at the round window is also lost.',
    concepts: ['physiology', 'middle-ear', 'ossicles'],
  },
  {
    id: 'q7',
    type: 'mcq',
    stem: 'Why does noise-induced hearing loss preferentially produce a notch at 4 kHz?',
    options: [
      { id: 'a', text: 'The cochlear apex is most vulnerable to high frequencies' },
      { id: 'b', text: 'The EAC resonance amplifies 3–4 kHz sounds by ~15 dB' },
      { id: 'c', text: 'The stapes footplate is tuned to 4 kHz' },
      { id: 'd', text: 'Outer hair cells are absent at the cochlear base' },
    ],
    correct: 'b',
    brief: 'EAC resonance at ~3500 Hz boosts sound energy in the 3–4 kHz range by ~15 dB.',
    detailed: 'The EAC functions as a quarter-wavelength resonator with peak amplification near 3500 Hz, delivering ~15 dB of passive gain. Combined with the basal cochlea\'s vulnerability (stiffer basilar membrane, high-frequency tonotopy, higher metabolic demand for OHCs), this concentrates noise damage at ~4 kHz — the classic audiometric notch. Lateral 1/3 of the EAC is cartilaginous; medial 2/3 is bony.',
    concepts: ['physiology', 'external-ear', 'NIHL', 'tonotopy'],
  },
  {
    id: 'q8',
    type: 'mcq',
    stem: 'Outer hair cell function is best evaluated by:',
    options: [
      { id: 'a', text: 'Auditory brainstem response (ABR)' },
      { id: 'b', text: 'Otoacoustic emissions (OAEs)' },
      { id: 'c', text: 'Tympanometry' },
      { id: 'd', text: 'Acoustic reflexes' },
    ],
    correct: 'b',
    brief: 'OAEs assess outer hair cell function via electromotile feedback to the basilar membrane.',
    detailed: 'OHCs amplify basilar membrane motion via electromotility (prestin protein) and produce otoacoustic emissions as a byproduct. Loss of OAEs indicates OHC dysfunction. In auditory neuropathy spectrum disorder (ANSD), OAEs are preserved (OHCs intact) but ABR is absent (synaptic or neural failure) — the classic decoupling. ABR evaluates the entire pathway; tympanometry assesses middle ear; acoustic reflexes test the stapedial reflex arc.',
    concepts: ['physiology', 'inner-ear', 'audiology', 'ANSD'],
  },
  {
    id: 'q9',
    type: 'mcq',
    stem: 'The base of the cochlea is most responsive to which frequencies?',
    options: [
      { id: 'a', text: 'Low frequencies (250–500 Hz)' },
      { id: 'b', text: 'Mid frequencies (1–2 kHz)' },
      { id: 'c', text: 'High frequencies (4–8 kHz)' },
      { id: 'd', text: 'Frequency-independent' },
    ],
    correct: 'c',
    brief: 'Tonotopy: basal cochlea (narrow, stiff basilar membrane) is high-frequency tuned; apex is low-frequency tuned.',
    detailed: 'The basilar membrane has a mechanical gradient — narrow and stiff at the base, wide and compliant at the apex. Sound produces a traveling wave that peaks at the location matching its frequency. This tonotopy is preserved by cochlear implant electrode arrays, with basal electrodes carrying high-frequency information. Hybrid/EAS strategies preserve apical acoustic hearing while electrically stimulating the base.',
    concepts: ['physiology', 'inner-ear', 'tonotopy', 'CI'],
  },
  {
    id: 'q10',
    type: 'mcq',
    stem: 'What proportion of pediatric hearing loss is conductive?',
    options: [
      { id: 'a', text: '10–20%' },
      { id: 'b', text: '40–50%' },
      { id: 'c', text: '70–80%' },
      { id: 'd', text: '90–95%' },
    ],
    correct: 'd',
    brief: 'CHL accounts for 90–95% of pediatric hearing loss, dominated by middle ear effusion.',
    detailed: 'Most pediatric CHL stems from acute otitis media or chronic otitis media with effusion — reflecting eustachian tube immaturity (short, horizontal, compliant) and high URI burden. Structural causes (atresia, ossicular fixation, cholesteatoma, trauma) are far less common but generally permanent and require imaging. Tympanostomy tubes are indicated for effusion persistent >3 months with hearing/speech concern, particularly in at-risk children (Down syndrome, cleft palate).',
    concepts: ['CHL', 'epidemiology'],
  },
  {
    id: 'q11',
    type: 'mcq',
    stem: 'In the Jahrsdoerfer scale for atresiaplasty candidacy, presence of the stapes is worth how many points?',
    options: [
      { id: 'a', text: '1 point' },
      { id: 'b', text: '2 points' },
      { id: 'c', text: '3 points' },
      { id: 'd', text: '5 points' },
    ],
    correct: 'b',
    brief: 'Stapes presence = 2 points (the only 2-point item); all other 8 parameters = 1 point each. Total = 10.',
    detailed: 'The Jahrsdoerfer scale weights stapes presence at 2 points because no functional ossicular reconstruction is possible without it. Remaining 1-point parameters: oval window open, middle ear space, facial nerve normal, malleus-incus complex present, mastoid pneumatization, incus-stapes connection, round window normal, external ear appearance. Scoring: 10 Excellent, 9 Very Good, 8 Good, 7 Fair, 6 Marginal, ≤5 Poor. Most surgeons require ≥7 for atresiaplasty candidacy.',
    concepts: ['CHL', 'atresia', 'jahrsdoerfer', 'surgical'],
  },
  {
    id: 'q12',
    type: 'mcq',
    stem: "According to Shannon et al.'s meta-analysis of aural atresia outcomes, which intervention shows greater hearing improvement?",
    options: [
      { id: 'a', text: 'Atresiaplasty alone' },
      { id: 'b', text: 'Bone conduction devices' },
      { id: 'c', text: 'No significant difference' },
      { id: 'd', text: 'Combined atresiaplasty + BCD' },
    ],
    correct: 'b',
    brief: 'BCDs showed 34.4 ± 1.6 dB gain vs. 22.4 ± 1.5 dB for atresiaplasty (p<0.0001), with fewer complications.',
    detailed: 'The Shannon meta-analysis tilts modern practice toward BCDs as first-line, especially in marginal Jahrsdoerfer scores. Atresiaplasty remains reasonable in Jahrsdoerfer ≥8 at experienced centers, offering more natural cosmesis and no external hardware. BCDs are primary for non-operable cases. Early soft-band BCD is now standard for both unilateral and bilateral atresia in infancy — even unilateral HL carries documented academic and behavioral risks.',
    concepts: ['CHL', 'atresia', 'surgical', 'BCD'],
  },
  {
    id: 'q13',
    type: 'mcq',
    stem: 'Congenital aural atresia is most commonly associated with:',
    options: [
      { id: 'a', text: 'Unilateral, left-sided, female predominance' },
      { id: 'b', text: 'Unilateral, right-sided, male predominance' },
      { id: 'c', text: 'Bilateral, no sex predominance' },
      { id: 'd', text: 'Bilateral, female predominance' },
    ],
    correct: 'b',
    brief: 'Congenital aural atresia is typically unilateral, right-sided, and more common in males.',
    detailed: 'Most cases are idiopathic and multifactorial. Syndromic associations include Treacher Collins (TCOF1), Goldenhar (hemifacial microsomia), and Crouzon syndrome. Atresia may be isolated or accompanied by microtia and ossicular abnormalities. Workup includes audiometry, careful exam for syndromic features, and CT temporal bone — typically deferred to age 4–5+ when surgical planning becomes relevant.',
    concepts: ['CHL', 'atresia', 'epidemiology', 'congenital'],
  },
  {
    id: 'q14',
    type: 'mcq',
    stem: 'A congenital cholesteatoma classically presents as:',
    options: [
      { id: 'a', text: 'White retraction pocket in the pars flaccida' },
      { id: 'b', text: 'White mass behind an intact tympanic membrane' },
      { id: 'c', text: 'Granulation tissue with chronic otorrhea' },
      { id: 'd', text: 'Pearly mass eroding the scutum' },
    ],
    correct: 'b',
    brief: 'Congenital cholesteatoma: white mass behind an intact TM, classically anterior-superior quadrant.',
    detailed: "Congenital cholesteatomas arise from epithelial rests that fail to involute embryologically (Michaels' epidermoid theory). Acquired cholesteatomas arise from retraction pockets — typically pars flaccida (attic) or posterosuperior pars tensa, often with scutum erosion. CT temporal bone shows non-dependent soft tissue density with possible bony erosion; non-EPI DWI MRI is gold standard for residual/recurrent disease surveillance, often replacing routine second-look surgery.",
    concepts: ['CHL', 'cholesteatoma', 'middle-ear'],
  },
  {
    id: 'q15',
    type: 'mcq',
    stem: 'The most common congenital ossicular anomaly is:',
    options: [
      { id: 'a', text: 'Absent long process of incus' },
      { id: 'b', text: 'Malleus-incus fusion' },
      { id: 'c', text: 'Congenital stapes footplate fixation' },
      { id: 'd', text: 'Stapes superstructure aplasia' },
    ],
    correct: 'c',
    brief: 'Congenital stapes footplate fixation is the most common congenital ossicular anomaly.',
    detailed: 'Congenital ossicular anomalies have an overall incidence of 0.5–1.2%, with ~25% syndromic. Stapes footplate fixation can mimic juvenile otosclerosis (low-frequency CHL, possible Carhart notch at 2 kHz) but is stable from birth rather than progressive. Always obtain CT before pediatric stapes surgery to exclude IP-III (Phelps/DFN3) — a potential perilymph gusher setup that contraindicates stapedotomy.',
    concepts: ['CHL', 'ossicles', 'congenital', 'DFN3'],
  },
  {
    id: 'q16',
    type: 'mcq',
    stem: 'The most common non-genetic cause of pediatric SNHL is:',
    options: [
      { id: 'a', text: 'Bacterial meningitis' },
      { id: 'b', text: 'Aminoglycoside ototoxicity' },
      { id: 'c', text: 'Congenital cytomegalovirus' },
      { id: 'd', text: 'Birth trauma' },
    ],
    correct: 'c',
    brief: 'Congenital CMV is the most common non-genetic cause of pediatric SNHL.',
    detailed: 'cCMV affects 0.5–2% of live births. Of symptomatic infants (~10–15% of those infected), ~50% develop SNHL. Of asymptomatic infants, ~7% develop SNHL — often delayed-onset. Diagnostic yield is higher in unilateral SNHL (~37%) than bilateral (~17%), making CMV particularly important in unilateral workup. Treatment with oral valganciclovir 32 mg/kg/day for 6 months improves hearing outcomes in symptomatic disease with CNS involvement or SNHL.',
    concepts: ['acquired-SNHL', 'cCMV', 'epidemiology'],
  },
  {
    id: 'q17',
    type: 'mcq',
    stem: 'The diagnostic window for distinguishing congenital from postnatally-acquired CMV is:',
    options: [
      { id: 'a', text: '7 days of life' },
      { id: 'b', text: '21 days of life' },
      { id: 'c', text: '90 days of life' },
      { id: 'd', text: '6 months of life' },
    ],
    correct: 'b',
    brief: 'PCR positive within 21 days of life confirms congenital infection.',
    detailed: 'Beyond 21 days, postnatal acquisition (via breast milk, contact) cannot be excluded by PCR. Retrospective dried blood spot (Guthrie card) testing has limited sensitivity (~70–80%). Postnatal CMV in term infants is generally benign; in preterm/NICU infants it can cause sequelae but is rarely a cause of permanent SNHL. Acceptable specimens within the window: urine, saliva, or dried blood spot PCR.',
    concepts: ['acquired-SNHL', 'cCMV', 'diagnosis'],
  },
  {
    id: 'q18',
    type: 'mcq',
    stem: 'First-line treatment for symptomatic congenital CMV with CNS involvement is:',
    options: [
      { id: 'a', text: 'IV ganciclovir for 6 weeks' },
      { id: 'b', text: 'Oral valganciclovir for 6 weeks' },
      { id: 'c', text: 'Oral valganciclovir for 6 months' },
      { id: 'd', text: 'IV foscarnet' },
    ],
    correct: 'c',
    brief: 'Oral valganciclovir 32 mg/kg/day divided BID for 6 months is current standard.',
    detailed: 'The Kimberlin trial (NEJM 2015) established 6 months of oral valganciclovir as superior to 6 weeks of IV ganciclovir for hearing and developmental outcomes. Monitor weekly CBC for neutropenia, the major adverse effect. Treatment of asymptomatic cCMV with isolated SNHL remains controversial; the ValEAR trial and others are addressing this question. Treatment of symptomatic cCMV with CNS involvement (calcifications, white matter changes, microcephaly) and/or SNHL is well established.',
    concepts: ['acquired-SNHL', 'cCMV', 'treatment'],
  },
  {
    id: 'q19',
    type: 'mcq',
    stem: 'Which MRI finding constellation is most suggestive of congenital CMV?',
    options: [
      { id: 'a', text: 'Cerebellar hypoplasia + anterior temporal lobe enhancement' },
      { id: 'b', text: 'Periventricular calcifications + polymicrogyria + cerebellar hypoplasia' },
      { id: 'c', text: 'Diffuse cortical atrophy + thinned corpus callosum' },
      { id: 'd', text: 'Hydrocephalus + diffuse parenchymal calcifications' },
    ],
    correct: 'b',
    brief: 'cCMV classically shows periventricular calcifications, polymicrogyria, cerebellar hypoplasia, and subependymal cysts.',
    detailed: 'First-trimester infection produces neuronal migration anomalies (polymicrogyria, lissencephaly, cerebellar hypoplasia) — worst neurodevelopmental prognosis. Second/third-trimester infection produces predominantly white matter signal change, calcifications, and germinolytic cysts with preserved cortex. Hydrocephalus + diffuse calcifications is more suggestive of toxoplasmosis. Temporal lobe enhancement is HSV.',
    concepts: ['acquired-SNHL', 'cCMV', 'imaging'],
  },
  {
    id: 'q20',
    type: 'mcq',
    stem: 'Which mitochondrial variant confers dose-independent susceptibility to aminoglycoside ototoxicity?',
    options: [
      { id: 'a', text: 'MT-TL1 (MELAS)' },
      { id: 'b', text: 'MT-TK (MERRF)' },
      { id: 'c', text: 'MT-RNR1 A1555G' },
      { id: 'd', text: 'MT-CO1' },
    ],
    correct: 'c',
    brief: 'A1555G in the mitochondrial 12S rRNA (MT-RNR1) causes dose-independent aminoglycoside ototoxicity.',
    detailed: 'Carriers can develop profound deafness from a single dose of aminoglycoside. The mutation is maternally inherited and affects ~1 in 500 individuals. Family history of HL after antibiotic exposure should prompt mitochondrial testing before any aminoglycoside use. MT-TS1 confers similar susceptibility. MT-TL1 and MT-TK underlie the multisystem MELAS and MERRF syndromes respectively, in which HL is part of a broader phenotype.',
    concepts: ['acquired-SNHL', 'ototoxicity', 'mitochondrial', 'mechanism'],
  },
  {
    id: 'q21',
    type: 'mcq',
    stem: 'GJB2 / Connexin 26 mutations cause hearing loss by:',
    options: [
      { id: 'a', text: 'Disrupting stereocilin in stereocilia tip links' },
      { id: 'b', text: 'Impairing endolymph production by the stria vascularis' },
      { id: 'c', text: 'Disrupting potassium recycling via gap junctions' },
      { id: 'd', text: 'Causing migration failure of neural crest melanocytes' },
    ],
    correct: 'c',
    brief: 'Connexin 26 forms gap junctions in supporting cells that recycle K⁺ from hair cells back to endolymph.',
    detailed: 'Hair cell depolarization requires K⁺ influx from endolymph. The spent K⁺ exits through the basolateral membrane and must return to endolymph via gap junctions of supporting cells, fibrocytes, and stria vascularis. GJB2 mutations disrupt this recycling, causing severe-to-profound SNHL despite normal inner ear anatomy. GJB2 accounts for 15–50% of AR non-syndromic deafness: 35delG most common in European descent, 167delT in Ashkenazi, 235delC in East Asians. Excellent CI candidates.',
    concepts: ['genetic-SNHL', 'GJB2', 'mechanism', 'potassium'],
  },
  {
    id: 'q22',
    type: 'mcq',
    stem: 'DFN3 (Phelps syndrome / X-linked stapes gusher) results from mutation in:',
    options: [
      { id: 'a', text: 'GJB2' },
      { id: 'b', text: 'POU3F4' },
      { id: 'c', text: 'SLC26A4' },
      { id: 'd', text: 'MYO7A' },
    ],
    correct: 'b',
    brief: 'DFN3 is caused by POU3F4 mutation, producing incomplete partition type III on imaging.',
    detailed: 'POU3F4 is a transcription factor; its disruption produces failure of bony separation between the IAC and cochlear base (incomplete partition type III). CT shows bulbous IAC with widened cochlear aperture. Clinical: mixed hearing loss, congenital stapes fixation, and catastrophic perilymph gusher with stapes surgery from abnormal CSF–perilymph communication. Always obtain CT before pediatric stapes surgery — IP-III contraindicates stapedotomy.',
    concepts: ['genetic-SNHL', 'syndromic-XL', 'DFN3', 'imaging', 'surgical'],
  },
  {
    id: 'q23',
    type: 'mcq',
    stem: "The EHDI '1:3:6 rule' refers to:",
    options: [
      { id: 'a', text: 'Screen by 1 year, diagnose by 3 years, intervene by 6 years' },
      { id: 'b', text: 'Screen by 1 month, diagnose by 3 months, intervene by 6 months' },
      { id: 'c', text: 'Re-screen at 1, 3, and 6 months for high-risk infants' },
      { id: 'd', text: 'Risk factor surveillance at 1, 3, and 6 months of age' },
    ],
    correct: 'b',
    brief: 'Screen by 1 month, audiologic evaluation of failures by 3 months, intervention by 6 months.',
    detailed: "Pre-EHDI, the average age of congenital HL diagnosis was ~2 years — well past the critical period for language. Yoshinaga-Itano's foundational work established that intervention before 6 months produces language outcomes statistically indistinguishable from normal-hearing peers. The aspirational target is now 1:2:3. Largest dropout is at the diagnostic step (loss to follow-up after failed screen). Ongoing surveillance from 2 months addresses delayed-onset/progressive HL, dominated by cCMV.",
    concepts: ['EHDI', 'screening', 'epidemiology'],
  },
  {
    id: 'q24',
    type: 'mcq',
    stem: 'For a 9-month-old infant, the most appropriate behavioral audiologic test is:',
    options: [
      { id: 'a', text: 'Soundfield observational audiometry (BOA)' },
      { id: 'b', text: 'Visual reinforcement audiometry (VRA)' },
      { id: 'c', text: 'Conditioned play audiometry (CPA)' },
      { id: 'd', text: 'Conventional audiometry' },
    ],
    correct: 'b',
    brief: 'VRA is appropriate for 6 months to 2.5 years; uses a visual reward paired with sound presentation.',
    detailed: 'Developmental ladder: 0–6 mo BOA (unreliable, large false-pass rate), 6 mo–2.5 yr VRA, 2.5–5 yr CPA, >5 yr conventional. For infants <6 months or uncooperative children, objective testing is required: ABR (entire pathway, threshold estimates), OAEs (OHC function), tympanometry (middle ear), acoustic reflexes (stapedial reflex arc, retrocochlear screen).',
    concepts: ['audiology', 'EHDI', 'workup'],
  },
  {
    id: 'q25',
    type: 'mcq',
    stem: 'In a child with bilateral severe-to-profound congenital SNHL, what targeted test screens for a treatable, potentially lethal syndrome?',
    options: [
      { id: 'a', text: 'Renal ultrasound' },
      { id: 'b', text: 'Thyroid function tests' },
      { id: 'c', text: 'EKG' },
      { id: 'd', text: 'Urinalysis' },
    ],
    correct: 'c',
    brief: 'EKG screens for Jervell and Lange-Nielsen syndrome (prolonged QT) in bilateral severe-to-profound SNHL.',
    detailed: 'JLN combines bilateral severe-to-profound SNHL with prolonged QT — untreated mortality ~50% by age 15 from ventricular arrhythmia. KCNQ1 and KCNE1 encode potassium channel subunits required for both cardiac repolarization (IKs) and endolymph K⁺ secretion by the stria vascularis. Treatment: beta-blockade ± ICD. Avoid QT-prolonging drugs (macrolides, ondansetron). Universal lab batteries are no longer recommended — phenotype-driven targeted testing has higher yield.',
    concepts: ['workup', 'JLN', 'syndromic-AR', 'potassium'],
  },
  {
    id: 'q26',
    type: 'mcq',
    stem: 'A child with preauricular pits, branchial cleft cysts, mixed hearing loss, and renal anomalies most likely has:',
    options: [
      { id: 'a', text: 'Treacher Collins syndrome' },
      { id: 'b', text: 'Branchio-Oto-Renal syndrome' },
      { id: 'c', text: 'Stickler syndrome' },
      { id: 'd', text: 'Pendred syndrome' },
    ],
    correct: 'b',
    brief: 'BOR syndrome — EYA1 mutation, AD inheritance, with branchial, otologic, and renal anomalies.',
    detailed: 'BOR (Branchio-Oto-Renal) is AD with EYA1 (chromosome 8q13.3) most common; SIX1, EYA2, EYA3, SIX5 also implicated. Otologic: preauricular pits/tags, microtia, auricular malformations, absent oval window, aberrant ossicles. Hearing loss is most often mixed. Branchial: cervical fistulas, sinuses, cysts in ~50%. Renal: agenesis most common, dysplasia, ureteral anomalies. Renal ultrasound is mandatory at diagnosis.',
    concepts: ['syndromic-AD', 'BOR'],
  },
  {
    id: 'q27',
    type: 'mcq',
    stem: 'Treacher Collins syndrome results from mutation in:',
    options: [
      { id: 'a', text: 'TCOF1 encoding treacle' },
      { id: 'b', text: 'CHD7' },
      { id: 'c', text: 'EYA1' },
      { id: 'd', text: 'PAX3' },
    ],
    correct: 'a',
    brief: 'TCOF1 on 5q32-33.1 encodes treacle protein, involved in neural crest cell ribosome biogenesis.',
    detailed: 'Treacher Collins (mandibulofacial dysostosis) is AD with 50% de novo mutations. Features: hypoplastic facial bones, downward-slanting palpebral fissures, lower eyelid coloboma with lash absence, micrognathia (airway concern in infancy), choanal atresia in some, ear atresia/ossicular anomalies, malformed oval window. Atresiaplasty is technically challenging due to distorted anatomy and aberrant facial nerve course; BCDs are often preferred.',
    concepts: ['syndromic-AD', 'treacher-collins', 'first-arch', 'atresia'],
  },
  {
    id: 'q28',
    type: 'mcq',
    stem: 'Waardenburg syndrome Type 1 is distinguished from Type 2 by the presence of:',
    options: [
      { id: 'a', text: 'Hirschsprung disease' },
      { id: 'b', text: 'Limb anomalies' },
      { id: 'c', text: 'Dystopia canthorum' },
      { id: 'd', text: 'More severe hearing loss' },
    ],
    correct: 'c',
    brief: 'Type 1 has dystopia canthorum (lateral displacement of medial canthi); Type 2 does not.',
    detailed: 'Type 1: with dystopia canthorum, PAX3. Type 2: without dystopia canthorum, MITF most common. Type 3 (Klein-Waardenburg): Type 1 features + limb anomalies, PAX3. Type 4 (Waardenburg-Shah): + Hirschsprung disease, EDNRB/EDN3/SOX10. All are neurocristopathies; SNHL results from melanocyte loss in the stria vascularis disrupting endocochlear potential maintenance — a mechanistic parallel to the K⁺ recycling failure in GJB2.',
    concepts: ['syndromic-AD', 'waardenburg', 'mechanism'],
  },
  {
    id: 'q29',
    type: 'mcq',
    stem: 'The three major diagnostic criteria for CHARGE syndrome (Verloes) are:',
    options: [
      { id: 'a', text: 'Coloboma, heart defect, choanal atresia' },
      { id: 'b', text: 'Coloboma, choanal atresia, hypoplastic semicircular canals' },
      { id: 'c', text: 'Choanal atresia, ear anomalies, growth retardation' },
      { id: 'd', text: 'Heart defect, genital hypoplasia, ear anomalies' },
    ],
    correct: 'b',
    brief: "Verloes' major criteria: coloboma, choanal atresia, hypoplastic semicircular canals.",
    detailed: 'CHARGE = Coloboma, Heart defect, Atresia of choanae, Retarded growth/development, Genital hypoplasia, Ear anomalies. CHD7 gene (chromosome 8) encodes a chromatin remodeling protein. Hypoplastic semicircular canals are highly characteristic on imaging. Cochlear implantation in CHARGE is challenging due to facial nerve aberrancy, hypoplastic mastoid, abnormal cochlear orientation, and frequent cochlear nerve hypoplasia.',
    concepts: ['syndromic-AD', 'CHARGE', 'imaging'],
  },
  {
    id: 'q30',
    type: 'mcq',
    stem: 'The most common autosomal recessive syndromic hearing loss is:',
    options: [
      { id: 'a', text: 'Usher syndrome' },
      { id: 'b', text: 'Pendred syndrome' },
      { id: 'c', text: 'Jervell and Lange-Nielsen' },
      { id: 'd', text: 'Alport syndrome' },
    ],
    correct: 'b',
    brief: 'Pendred syndrome (SLC26A4) is the most common AR syndromic HL.',
    detailed: 'SLC26A4 encodes pendrin — a chloride/iodide/bicarbonate transporter expressed in thyroid (iodide organification) and inner ear (endolymph homeostasis). Hallmarks: euthyroid goiter in the second decade with positive perchlorate discharge test, and inner ear malformations (enlarged vestibular aqueduct + incomplete partition type II/Mondini). Hearing loss is variable — SNHL, conductive (third-window effect from EVA), or mixed — often progressive or fluctuating with head trauma. Counsel avoidance of contact sports and pressure changes.',
    concepts: ['syndromic-AR', 'pendred', 'EVA'],
  },
  {
    id: 'q31',
    type: 'mcq',
    stem: 'Which Usher syndrome subtype features delayed motor milestones from vestibular areflexia?',
    options: [
      { id: 'a', text: 'Type 1' },
      { id: 'b', text: 'Type 2' },
      { id: 'c', text: 'Type 3' },
      { id: 'd', text: 'Type 4' },
    ],
    correct: 'a',
    brief: 'Usher Type 1 = profound congenital HL + vestibular areflexia + prepubertal retinitis pigmentosa.',
    detailed: 'Type 1: profound HL + vestibular areflexia (delayed sitting, walking) + prepubertal RP, often MYO7A. Type 2: moderate-severe HL + normal vestibular + pubertal RP, USH2A. Type 3: progressive HL + variable vestibular + post-pubertal RP. Type 1 is most relevant for pediatric ENT: identify at newborn screen, watch for motor delay, refer to ophthalmology for ERG (more sensitive than fundoscopy in young children), and consider early bilateral CI before vision loss progresses.',
    concepts: ['syndromic-AR', 'usher', 'vestibular', 'CI'],
  },
  {
    id: 'q32',
    type: 'mcq',
    stem: 'The most common inner ear malformation seen on imaging in pediatric SNHL is:',
    options: [
      { id: 'a', text: 'Mondini deformity (incomplete partition type II)' },
      { id: 'b', text: 'Enlarged vestibular aqueduct' },
      { id: 'c', text: 'Cochlear nerve aplasia' },
      { id: 'd', text: 'Common cavity deformity' },
    ],
    correct: 'b',
    brief: 'EVA is the most common radiologic abnormality in pediatric SNHL, often associated with Pendred syndrome.',
    detailed: 'EVA is defined as vestibular aqueduct midpoint diameter >1.5 mm (Valvassori) or >2 mm at operculum (Cincinnati criterion). Often associated with IP-II (Mondini). SLC26A4 mutations underlie Pendred when bilateral. EVA can produce CHL (third-window effect), SNHL, or mixed loss — often progressive with head trauma. Surgical caveat: higher CSF gusher risk at cochleostomy during CI.',
    concepts: ['imaging', 'EVA', 'syndromic-AR', 'pendred'],
  },
  {
    id: 'q33',
    type: 'mcq',
    stem: 'Alport syndrome results from mutations in genes encoding:',
    options: [
      { id: 'a', text: 'Type II collagen' },
      { id: 'b', text: 'Type IV collagen' },
      { id: 'c', text: 'Pendrin' },
      { id: 'd', text: 'Otoferlin' },
    ],
    correct: 'b',
    brief: 'Mutations in COL4A3, COL4A4, COL4A5 (type IV collagen) cause Alport syndrome.',
    detailed: 'Type IV collagen forms the glomerular basement membrane, cochlear basement membrane, and lens capsule. Clinical diagnosis requires 4 of: family history of hematuria, high-frequency SNHL, ocular changes (anterior lenticonus), GBM changes on biopsy. Most common inheritance is X-linked. High-frequency SNHL often precedes renal failure — urinalysis is reasonable screening in progressive high-frequency loss. Renal transplant may be needed in late adolescence.',
    concepts: ['syndromic-XL', 'alport', 'collagen'],
  },
  {
    id: 'q34',
    type: 'mcq',
    stem: 'Jervell and Lange-Nielsen syndrome results from mutation in which gene class?',
    options: [
      { id: 'a', text: 'Collagen genes' },
      { id: 'b', text: 'Connexin genes' },
      { id: 'c', text: 'Potassium channel genes' },
      { id: 'd', text: 'Myosin genes' },
    ],
    correct: 'c',
    brief: 'KCNQ1 and KCNE1 encode potassium channel subunits required for both cardiac repolarization and endolymph K⁺ secretion.',
    detailed: 'The same IKs channel is required for cardiac repolarization and for K⁺ secretion by the stria vascularis — explaining the dual phenotype of bilateral severe-to-profound SNHL + prolonged QT. JLN is AR; the heterozygous state produces Romano-Ward syndrome (long QT without HL). Treatment: beta-blockade ± ICD. Avoid QT-prolonging drugs. CI is safe with cardiology clearance and anesthetic precautions.',
    concepts: ['syndromic-AR', 'JLN', 'potassium', 'mechanism'],
  },
  {
    id: 'q35',
    type: 'mcq',
    stem: 'For most pediatric SNHL imaging workup, the preferred first-line study is:',
    options: [
      { id: 'a', text: 'CT temporal bone' },
      { id: 'b', text: 'MRI internal auditory canal' },
      { id: 'c', text: 'Plain temporal bone radiograph' },
      { id: 'd', text: 'Ultrasound of the neck' },
    ],
    correct: 'b',
    brief: 'MRI IAC is preferred first — no radiation, evaluates brain, detects cochlear nerve aplasia.',
    detailed: 'MRI advantages: no radiation, evaluates brain (cCMV findings, kernicterus, migration anomalies), detects cochlear nerve presence/absence (critical pre-CI), resolves most inner ear anomalies. <6 months feed-and-sleep is feasible; older requires anesthesia. CT advantages: superior bony detail (IP-III, EVA dimensions, ossicles), labyrinthitis ossificans assessment, atresiaplasty planning. Both may be needed for CHARGE, BOR, DFN3, or post-meningitis surveillance.',
    concepts: ['imaging', 'workup'],
  },
  {
    id: 'q36',
    type: 'mcq',
    stem: 'Following bacterial meningitis with profound SNHL, why is urgent cochlear implantation often recommended?',
    options: [
      { id: 'a', text: 'Restoration of vestibular function' },
      { id: 'b', text: 'Prevention of labyrinthine ossification preventing electrode insertion' },
      { id: 'c', text: 'To allow simultaneous antibiotic delivery' },
      { id: 'd', text: 'Higher CI outcomes shortly after meningitis' },
    ],
    correct: 'b',
    brief: 'Post-meningitis labyrinthitis ossificans can begin within weeks, potentially preventing electrode insertion.',
    detailed: 'Streptococcus pneumoniae meningitis is the most common cause. Bony obliteration of the scala tympani can begin within weeks, scarring the cochlear lumen and making conventional electrode insertion impossible. Serial MRI surveillance is critical — loss of fluid signal in the cochlea on T2 suggests fibrosis preceding ossification. Urgent CI may be required even before optimal pre-op preparation.',
    concepts: ['surgical', 'CI', 'meningitis', 'acquired-SNHL'],
  },
  {
    id: 'q37',
    type: 'mcq',
    stem: 'A 3-month-old with right Grade III microtia/aural atresia and right CHL (~50–60 dB), normal left hearing. What is the most appropriate initial amplification?',
    options: [
      { id: 'a', text: 'Watchful waiting until school age' },
      { id: 'b', text: 'Soft-band BCD on the right' },
      { id: 'c', text: 'Bilateral hearing aids' },
      { id: 'd', text: 'Cochlear implant' },
    ],
    correct: 'b',
    brief: 'Early soft-band BCD on the right side is standard — unilateral HL carries documented academic and developmental risks.',
    detailed: 'Even with a normal contralateral ear, unilateral hearing loss carries ~10× higher rates of grade retention, behavioral difficulties, and IEP utilization. Children lose binaural summation, squelch, head shadow benefit, and spatial release from masking. Soft-band BAHA delivers bone-conducted sound bypassing the atresia. Osseointegrated implants are deferred to age 5+ when temporal bone thickness permits stable integration (≥3 mm). CT and atresiaplasty vs. BCD decision-making typically wait until age 4–5+.',
    concepts: ['cases', 'atresia', 'BCD', 'CHL'],
  },
  {
    id: 'q38',
    type: 'mcq',
    stem: 'A 3-day-old with failed newborn screen, blueberry muffin rash, and MRI showing periventricular calcifications. The diagnostic and treatment priority is:',
    options: [
      { id: 'a', text: 'Send broad genetic panel first' },
      { id: 'b', text: 'CMV PCR within 21 days; valganciclovir 6 months if positive with CNS/SNHL findings' },
      { id: 'c', text: 'Empiric acyclovir for HSV coverage' },
      { id: 'd', text: 'Defer testing pending clinical evolution' },
    ],
    correct: 'b',
    brief: 'CMV PCR within the 21-day window confirms congenital infection; valganciclovir 6 months for symptomatic disease with CNS/SNHL involvement.',
    detailed: 'Beyond 21 days, postnatal acquisition cannot be excluded by PCR. Urine, saliva, or dried blood spot PCR are all acceptable. Symptomatic cCMV with CNS findings and/or SNHL is the standard treatment indication. Monitor weekly CBC for neutropenia. Long-term audiologic surveillance is essential — delayed-onset and progressive HL can occur years later (~7% of asymptomatic cCMV infants develop delayed HL).',
    concepts: ['cases', 'cCMV', 'treatment', 'diagnosis'],
  },
  {
    id: 'q39',
    type: 'mcq',
    stem: 'A 3-week-old with bilateral severe-to-profound SNHL, GJB2-positive, no other risk factors. Long-term expectations include:',
    options: [
      { id: 'a', text: 'Progressive hearing loss requiring repeated audiologic reprogramming' },
      { id: 'b', text: 'Stable HL with excellent cochlear implant outcomes' },
      { id: 'c', text: 'High likelihood of associated syndromic features developing' },
      { id: 'd', text: 'Need for staged middle ear exploration' },
    ],
    correct: 'b',
    brief: 'GJB2 phenotype is the textbook CI candidate: stable severe-to-profound prelingual SNHL with normal anatomy and excellent outcomes.',
    detailed: 'GJB2 (DFNB1, Connexin 26) accounts for 15–50% of AR non-syndromic SNHL. Hearing is typically stable from birth, normal inner ear anatomy, normal cochlear nerve, no syndromic features. FDA approved CI at ≥9 months for severe-to-profound bilateral SNHL. Bilateral simultaneous CI is now standard when bilateral profound SNHL is confirmed — binaural benefits include localization, speech in noise, reduced listening effort. Sequential second-side CI should be considered within ~3–4 years for best outcomes.',
    concepts: ['cases', 'GJB2', 'CI', 'genetic-SNHL'],
  },
  {
    id: 'q40',
    type: 'mcq',
    stem: 'Gene therapy for which deafness gene has shown the most clinical success to date?',
    options: [
      { id: 'a', text: 'GJB2' },
      { id: 'b', text: 'MYO7A' },
      { id: 'c', text: 'OTOF' },
      { id: 'd', text: 'SLC26A4' },
    ],
    correct: 'c',
    brief: 'AAV-mediated OTOF replacement has restored hearing in children with auditory neuropathy from DFNB9.',
    detailed: 'Otoferlin mediates synaptic vesicle fusion at inner hair cell ribbon synapses — its loss produces ANSD (preserved OAEs, absent ABR). OTOF is small enough to fit into AAV vectors; many other deafness genes (MYO7A, CDH23) are too large, requiring dual-vector strategies. Multiple trials (Chinese, US, European) have demonstrated hearing restoration within weeks of inner ear injection, with durability beyond 1 year. Genetic testing pre-CI is increasingly important to identify potential gene therapy candidates.',
    concepts: ['emerging', 'gene-therapy', 'ANSD'],
  },
];

window.__MCQ_MODULE = { meta, DOMAINS, CONCEPTS, ITEMS };
