// ─────────────────────────────────────────────────────────────────────
// MODULE · Pediatric OR Primer — Tubes, Tonsils & Neck
// Source: Pediatric Otolaryngology OR Day Study Guide (direct Q&A → MCQ)
// Schema: { meta, DOMAINS, CONCEPTS, ITEMS }
// ─────────────────────────────────────────────────────────────────────

const meta = {
  id: 'ta-tubes',
  title: 'Tubes, Tonsils\n& Neck',
  subtitle:
    'Fifty-four MCQs across myringotomy and tubes, adeno-/tonsillectomy (extra- and intracapsular), Level II neck node excision, and the operative complications and case integrations that tie them together. Answers reveal the operative rationale; concept tags link related decisions across procedures.',
  kicker: 'OCC · Pediatric OR Primer',
};

const DOMAINS = {
  foundations: { label: 'Foundations', color: '#8B6F47', hex: 'rgba(139,111,71,0.12)' },
  bmt: { label: 'Tubes & OME', color: '#7B6B85', hex: 'rgba(123,107,133,0.14)' },
  tonsillectomy: { label: 'Tonsillectomy', color: '#A0635E', hex: 'rgba(160,99,94,0.14)' },
  neck: { label: 'Neck Node', color: '#2C5454', hex: 'rgba(44,84,84,0.14)' },
  complications: { label: 'Complications', color: '#7B7B4A', hex: 'rgba(123,123,74,0.14)' },
  cases: { label: 'Integration', color: '#8B4513', hex: 'rgba(139,69,19,0.14)' },
};

const CONCEPTS = {
  // foundations
  embryology: { label: 'Embryology', domain: 'foundations' },
  'tm-anatomy': { label: 'TM Anatomy', domain: 'foundations' },
  'middle-ear': { label: 'Middle Ear', domain: 'foundations' },
  'eustachian-tube': { label: 'Eustachian Tube', domain: 'foundations' },
  physiology: { label: 'Physiology', domain: 'foundations' },
  'tonsil-anatomy': { label: 'Tonsil Anatomy', domain: 'foundations' },
  'adenoid-anatomy': { label: 'Adenoid Anatomy', domain: 'foundations' },
  waldeyer: { label: 'Waldeyer Ring', domain: 'foundations' },
  'cranial-nerves': { label: 'Cranial Nerves', domain: 'foundations' },
  imaging: { label: 'Imaging', domain: 'foundations' },
  workup: { label: 'Workup', domain: 'foundations' },
  // tubes / OME
  OME: { label: 'OME', domain: 'bmt' },
  tubes: { label: 'PE Tubes', domain: 'bmt' },
  myringotomy: { label: 'Myringotomy', domain: 'bmt' },
  tympanometry: { label: 'Tympanometry', domain: 'bmt' },
  SSCD: { label: 'SSCD', domain: 'bmt' },
  // tonsillectomy
  OSA: { label: 'OSA / SDB', domain: 'tonsillectomy' },
  brodsky: { label: 'Brodsky Grade', domain: 'tonsillectomy' },
  extracapsular: { label: 'Extracapsular', domain: 'tonsillectomy' },
  intracapsular: { label: 'Intracapsular', domain: 'tonsillectomy' },
  capsule: { label: 'Capsule', domain: 'tonsillectomy' },
  'tonsil-dissection': { label: 'Tonsil Dissection', domain: 'tonsillectomy' },
  adenoidectomy: { label: 'Adenoidectomy', domain: 'tonsillectomy' },
  'tonsillar-artery': { label: 'Tonsillar Artery', domain: 'tonsillectomy' },
  regrowth: { label: 'Regrowth', domain: 'tonsillectomy' },
  'dissection-plane': { label: 'Dissection Plane', domain: 'tonsillectomy' },
  hemostasis: { label: 'Hemostasis', domain: 'tonsillectomy' },
  // neck
  'nodal-anatomy': { label: 'Nodal Anatomy', domain: 'neck' },
  lymphadenitis: { label: 'Lymphadenitis', domain: 'neck' },
  'node-malignancy': { label: 'Benign vs Malignant', domain: 'neck' },
  'node-dissection': { label: 'Node Dissection', domain: 'neck' },
  'spinal-accessory': { label: 'CN XI (SAN)', domain: 'neck' },
  carotid: { label: 'Carotid / IJV', domain: 'neck' },
  // complications
  hemorrhage: { label: 'Hemorrhage', domain: 'complications' },
  VPI: { label: 'VPI', domain: 'complications' },
  dysphagia: { label: 'Dysphagia', domain: 'complications' },
  'tube-complications': { label: 'Tube Sequelae', domain: 'complications' },
  'airway-edema': { label: 'Airway Edema', domain: 'complications' },
  horner: { label: 'Horner Syndrome', domain: 'complications' },
  // cases
  cases: { label: 'Clinical Cases', domain: 'cases' },
  anesthesia: { label: 'Anesthesia', domain: 'cases' },
  counseling: { label: 'Counseling', domain: 'cases' },
  seizure: { label: 'Seizure Disorder', domain: 'cases' },
  'cochlear-implant': { label: 'Cochlear Implant', domain: 'cases' },
};

const ITEMS = [
  // ─────────────── FOUNDATIONS ───────────────
  {
    id: 'q1',
    type: 'mcq',
    stem: 'The middle ear cleft (tympanic cavity, antrum, mastoid air cells) is derived embryologically from:',
    options: [
      { id: 'a', text: 'The first pharyngeal cleft (groove)' },
      { id: 'b', text: 'The first pharyngeal pouch (tubotympanic recess)' },
      { id: 'c', text: 'The otic placode / otocyst' },
      { id: 'd', text: 'Second-arch (Reichert) cartilage' },
    ],
    correct: 'b',
    brief: 'The first pharyngeal pouch endoderm balloons laterally as the tubotympanic recess, becoming the eustachian tube and middle ear cleft.',
    detailed: 'Keep the germ layers straight: the first pharyngeal POUCH (endoderm) → eustachian tube + middle ear cleft, lined by respiratory/cuboidal mucosa. The first pharyngeal CLEFT/groove (ectoderm) → external auditory canal. The otic placode → membranous labyrinth (inner ear). The ossicles are a separate story: malleus head and incus body from first-arch (Meckel) cartilage, and the long process of incus, manubrium, and stapes superstructure from second-arch (Reichert) cartilage — so "Reichert forms the ossicles" is only half right.',
    concepts: ['embryology', 'middle-ear', 'eustachian-tube'],
  },
  {
    id: 'q2',
    type: 'mcq',
    stem: 'Compared with the adult, the tympanic membrane of an 18-month-old is:',
    options: [
      { id: 'a', text: 'More vertically oriented, thin, and highly compliant' },
      { id: 'b', text: 'More horizontally oriented, thicker, and less compliant' },
      { id: 'c', text: 'Identical in orientation but smaller in absolute area' },
      { id: 'd', text: 'Pars-flaccida dominant with an absent pars tensa' },
    ],
    correct: 'b',
    brief: 'The infant TM lies more horizontally and is thicker/stiffer, which both obscures the view and helps explain poor sound transmission in OME.',
    detailed: 'The pediatric TM is proportionally larger, more horizontal (lying near the canal floor), and thicker/less compliant than the adult drum, with a prominent anterior malleus handle as the key landmark. The horizontal lie makes visualization harder and the increased stiffness contributes to conductive loss when effusion is present. This same horizontal geometry of the canal and drum is why pneumatic otoscopy and a good cerumen-free view matter so much in this age group.',
    concepts: ['tm-anatomy', 'OME', 'middle-ear'],
  },
  {
    id: 'q3',
    type: 'mcq',
    stem: 'The eustachian tube is opened actively during swallowing and yawning primarily by which muscle, and how does it change with age?',
    options: [
      { id: 'a', text: 'Tensor tympani (CN V3); becomes more horizontal with age' },
      { id: 'b', text: 'Tensor veli palatini (CN V3); becomes more vertical and stiffer with age' },
      { id: 'c', text: 'Levator veli palatini (CN X); shortens with age' },
      { id: 'd', text: 'Salpingopharyngeus (CN X); becomes more horizontal with age' },
    ],
    correct: 'b',
    brief: 'Tensor veli palatini (CN V3) dilates the ET; the young child\'s short, horizontal, compliant tube verticalizes and stiffens by age 6–7.',
    detailed: 'The tensor veli palatini — not the tensor tympani — is the active dilator of the eustachian tube, innervated by the mandibular division of the trigeminal nerve (V3). In young children the ET is short, horizontal, and floppy, and the adenoid pad at the tubal torus can obstruct drainage, all predisposing to OME. By 6–7 years the tube verticalizes and stiffens, improving self-clearance — the anatomic basis for why most childhood OME is outgrown. The levator veli palatini (CN X) elevates the palate but is not the principal ET dilator.',
    concepts: ['eustachian-tube', 'cranial-nerves', 'OME'],
  },
  {
    id: 'q4',
    type: 'mcq',
    stem: 'A toddler with mucoid OME has a conductive loss. What air-bone gap and mechanism best fit?',
    options: [
      { id: 'a', text: '10–15 dB ABG from loss of the middle-ear lever ratio alone' },
      { id: 'b', text: '30–40 dB ABG from added mass/impedance of the effusion and stiffened TM' },
      { id: 'c', text: '50–60 dB ABG, implying complete ossicular discontinuity' },
      { id: 'd', text: 'No ABG; the loss is sensorineural' },
    ],
    correct: 'b',
    brief: 'Mucoid effusion adds mass and impedance and stiffens the drum, dampening transmission — typically a 30–40 dB conductive gap.',
    detailed: 'Effusion loads the system with mass and high impedance so the ossicular chain cannot respond efficiently to TM vibration, preferentially attenuating higher frequencies (a low-pass effect). The result is a 30–40 dB air-bone gap with normal bone-conduction thresholds. A gap approaching 50–60 dB suggests ossicular discontinuity, and an elevated bone line means a sensorineural or mixed component — both reasons to image or pursue ABR/OAE before attributing everything to simple OME.',
    concepts: ['physiology', 'OME', 'middle-ear'],
  },
  {
    id: 'q5',
    type: 'mcq',
    stem: 'During tonsillectomy, the major arterial bleeder is encountered at the inferior pole. Its origin is:',
    options: [
      { id: 'a', text: 'Tonsillar branch of the facial artery' },
      { id: 'b', text: 'Ascending pharyngeal artery directly off the ICA' },
      { id: 'c', text: 'Lingual artery within the tonsillar fossa' },
      { id: 'd', text: 'A branch of the internal carotid artery' },
    ],
    correct: 'a',
    brief: 'The dominant tonsillar artery is a branch of the facial artery (external carotid system) entering at the inferior pole.',
    detailed: 'Tonsillar blood supply is all external-carotid: the tonsillar branch of the facial artery (dominant, inferior pole), ascending pharyngeal, lesser palatine, lingual (dorsal lingual), and ascending palatine branches. The internal carotid carries no tonsillar branches but sits ~2–3 cm deep and lateral to the fossa — catastrophic if the dissection strays lateral to the superior constrictor. The lingual artery runs deep to the tongue base, not within the fossa, but is at risk with overly deep inferior-pole dissection. Knowing the inferior pole is the vascular pedicle drives proactive hemostasis there.',
    concepts: ['tonsil-anatomy', 'tonsillar-artery', 'carotid'],
  },
  {
    id: 'q6',
    type: 'mcq',
    stem: 'Which statement about the palatine tonsil versus the adenoid (pharyngeal tonsil) is correct?',
    options: [
      { id: 'a', text: 'Both have a true fibrous capsule, permitting clean extracapsular planes' },
      { id: 'b', text: 'The palatine tonsil has a fibrous capsule; the adenoid lacks one, making adenoidectomy a curette/ablation rather than a plane dissection' },
      { id: 'c', text: 'The adenoid arises from the first pharyngeal pouch; the palatine tonsil from the otic placode' },
      { id: 'd', text: 'Neither contains germinal centers, as both are primary lymphoid organs' },
    ],
    correct: 'b',
    brief: 'The palatine tonsil sits in a dissectable fibrous capsule; the adenoid has no capsule, so it is curetted/ablated against the nasopharyngeal roof.',
    detailed: 'Both are secondary lymphoid tissue (germinal centers, antigen surveillance) of the second pharyngeal pouch region, part of Waldeyer ring. The crucial surgical difference: the palatine tonsil has a fibrous capsule (pharyngeal-wall fascia) that defines the extracapsular dissection plane against the superior constrictor, whereas the adenoid is uncapsulated — historically a "blind" curette procedure (now often endoscopic suction-cautery or microdebrider) sweeping the nasopharyngeal roof. Adenoid bulk peaks at 3–5 years then regresses, which is why adenoid-dominant obstruction is an early-childhood problem.',
    concepts: ['embryology', 'adenoid-anatomy', 'tonsil-anatomy', 'capsule'],
  },
  {
    id: 'q7',
    type: 'mcq',
    stem: 'Waldeyer ring comprises the palatine tonsils, adenoid, lingual tonsil, and tubal tonsils. What is the expected immune consequence of tonsillectomy in a child?',
    options: [
      { id: 'a', text: 'Permanent humoral immunodeficiency requiring IgG monitoring' },
      { id: 'b', text: 'No measurable change in systemic immunity' },
      { id: 'c', text: 'A modest, transient rise in upper/lower respiratory infections without long-term immunodeficiency' },
      { id: 'd', text: 'Loss of mucosal IgA production throughout the gut' },
    ],
    correct: 'c',
    brief: 'Removing the palatine tonsils causes at most a small, transient infection increase; Waldeyer redundancy preserves long-term immunity.',
    detailed: 'Waldeyer ring is first-line mucosal immune surveillance, but its components are redundant. Tonsillectomy produces, at most, a modest transient increase in respiratory infections and no durable systemic immunodeficiency. This is why the immune "cost" is acceptable when the indication is airway obstruction (OSA). When the indication is infection alone, the calculus is different — recurrent throat infection now meets Paradise thresholds before surgery is justified, weighing infection burden against the tonsils\' surveillance role.',
    concepts: ['waldeyer', 'tonsil-anatomy', 'counseling'],
  },
  // ─────────────── TUBES & OME ───────────────
  {
    id: 'q8',
    type: 'mcq',
    stem: 'Per AAO-HNS guidance, which child most clearly meets criteria for tympanostomy tubes?',
    options: [
      { id: 'a', text: 'Unilateral OME for 6 weeks, no hearing concern' },
      { id: 'b', text: 'Bilateral OME ≥3 months with documented hearing loss ≥20 dB or speech/developmental concern' },
      { id: 'c', text: 'A single episode of acute otitis media' },
      { id: 'd', text: 'Bilateral OME for 4 weeks in an otherwise well child' },
    ],
    correct: 'b',
    brief: 'Tubes are indicated for chronic bilateral OME (≥3 months) with hearing loss or developmental impact; short-duration/unilateral disease without hearing loss is watched.',
    detailed: 'The guideline anchors on persistence + functional impact: bilateral OME ≥3 months with hearing loss (≥20 dB ABG) or documented speech/developmental concern favors tubes. Roughly half of effusions resolve spontaneously by 3 months, so brief or unilateral OME without hearing loss is watchful-waited. The critical-period argument sharpens this in toddlers — degraded auditory input during the explosive 12–24 month vocabulary window is itself a red flag, lowering the threshold to intervene even when formal audiometry is hard to obtain.',
    concepts: ['OME', 'tubes', 'workup'],
  },
  {
    id: 'q9',
    type: 'mcq',
    stem: 'Which is an ABSOLUTE contraindication to proceeding with tube placement today?',
    options: [
      { id: 'a', text: 'Down syndrome with eustachian-tube dysfunction' },
      { id: 'b', text: 'Active acute otitis externa / acute URI' },
      { id: 'c', text: 'Cleft palate' },
      { id: 'd', text: 'History of prior tube extrusion' },
    ],
    correct: 'b',
    brief: 'Active otitis externa or acute URI should defer surgery; craniofacial/syndromic conditions are relative factors that change tube choice, not absolute bars.',
    detailed: 'Absolute reasons to delay are active infection — acute otitis externa or an active URI (defer ~2–3 weeks). Relative considerations (Down syndrome, cleft palate, immunodeficiency, cystic fibrosis) raise the risk of obstruction, recurrence, or extrusion and push toward longer-term tubes and closer follow-up, but they are not contraindications. In fact stiff, immobile tympanograms with mucoid effusion are an indication for tubes, not a reason to avoid them — just rule out an active infection first.',
    concepts: ['tubes', 'OME'],
  },
  {
    id: 'q10',
    type: 'mcq',
    stem: 'A young child has UNILATERAL conductive loss attributed to OME. Before crediting OME alone, the key pearl is to:',
    options: [
      { id: 'a', text: 'Proceed straight to tubes; unilateral OME never needs further workup' },
      { id: 'b', text: 'Obtain age-appropriate audiometry and consider SNHL, congenital CMV, or a structural ossicular/canal anomaly' },
      { id: 'c', text: 'Start a 6-month antibiotic course before any testing' },
      { id: 'd', text: 'Order an EKG to exclude Jervell and Lange-Nielsen' },
    ],
    correct: 'b',
    brief: 'Asymmetric/unilateral loss should prompt formal audiometry and a search for SNHL, cCMV, or a structural anomaly before assuming simple OME.',
    detailed: 'Unilateral or markedly asymmetric loss is the trap: it can mask underlying SNHL, congenital CMV (higher diagnostic yield in unilateral SNHL than bilateral), or a structural cause such as ossicular/footplate fixation or canal atresia. Get age-appropriate behavioral audiometry (VRA in this age) and confirm the bone line; if any ear has disproportionately worse thresholds, image before placing tubes. The EKG distractor belongs to a different scenario — bilateral severe-to-profound SNHL screening for prolonged QT.',
    concepts: ['OME', 'workup', 'imaging'],
  },
  {
    id: 'q11',
    type: 'mcq',
    stem: 'Which tympanic-membrane quadrant is the safest site for myringotomy and tube placement, and which must be avoided?',
    options: [
      { id: 'a', text: 'Place posterosuperior; avoid anteroinferior' },
      { id: 'b', text: 'Place anteroinferior (pars tensa); avoid the posterosuperior quadrant' },
      { id: 'c', text: 'Place in the pars flaccida; avoid the pars tensa' },
      { id: 'd', text: 'Place at the umbo; avoid the annulus' },
    ],
    correct: 'b',
    brief: 'The anteroinferior pars tensa is the safe target; the posterosuperior quadrant overlies the ossicular chain, round window, and chorda tympani and must be avoided.',
    detailed: 'The incision goes in the anteroinferior quadrant of the pars tensa: away from the malleus handle anteriorly, allowing dependent drainage, and well clear of the danger zone. The posterosuperior quadrant overlies the incudostapedial joint, stapes/oval window, round window niche, and chorda tympani — a slip here risks ossicular trauma, sensorineural loss, or taste disturbance. The pars flaccida is avoided entirely (retraction-pocket/cholesteatoma risk). Keep the blade perpendicular to the drum; lateral-to-medial angulation courts ossicular/inner-ear injury.',
    concepts: ['myringotomy', 'middle-ear', 'tm-anatomy'],
  },
  {
    id: 'q12',
    type: 'mcq',
    stem: 'For a first-time, otherwise healthy toddler with mucoid OME, the appropriate tube and rationale is:',
    options: [
      { id: 'a', text: 'Long-term T-tube, because mucoid (thick) effusion mandates years of ventilation' },
      { id: 'b', text: 'Short-term grommet, expected to extrude in ~6–12 months as the TM epithelium migrates' },
      { id: 'c', text: 'No tube; mucoid effusion always resolves within days' },
      { id: 'd', text: 'Long-term T-tube, because the child is under 2 years old' },
    ],
    correct: 'b',
    brief: 'Grommets suit first-time, presumed self-limited OME; T-tubes are reserved for recurrent disease or syndromic ET dysfunction.',
    detailed: 'A short-term grommet (typical dwell 6–12 months) is standard for first-time tubes in presumed self-limited OME; it extrudes as TM epithelium migrates laterally. T-tubes (2–5 year dwell) are for recurrent/chronic OME after grommet extrusion or for syndromic ET dysfunction (Down, cleft) — but they carry a higher rate of persistent perforation. The mucoid character of the effusion is typical and does not by itself dictate a long-term tube; the fluid resorbs once ventilation is restored.',
    concepts: ['tubes', 'OME'],
  },
  {
    id: 'q13',
    type: 'mcq',
    stem: 'In the ventilation–clearance–defense model of OME, tympanostomy tubes directly address which component?',
    options: [
      { id: 'a', text: 'Clearance (restoring mucociliary transport)' },
      { id: 'b', text: 'Defense (eliminating biofilm and viral inflammation)' },
      { id: 'c', text: 'Ventilation (bypassing ET dysfunction to equalize pressure and allow gas exchange)' },
      { id: 'd', text: 'All three equally' },
    ],
    correct: 'c',
    brief: 'Tubes restore middle-ear ventilation/pressure equilibration but do nothing for mucociliary clearance or immune/biofilm factors.',
    detailed: 'OME pathogenesis braids together ventilation (ET dysfunction), clearance (mucociliary failure), and defense (viral inflammation, biofilm). A tube is a mechanical bypass of the ventilation problem only — it equalizes pressure and permits gas diffusion. It does not improve mucociliary clearance or alter immune/biofilm contributors, which is precisely why effusion can recur or otorrhea can persist even with a patent tube in place if those drivers continue.',
    concepts: ['OME', 'tubes'],
  },
  {
    id: 'q14',
    type: 'mcq',
    stem: 'The most common intraoperative complication of pediatric tube placement is:',
    options: [
      { id: 'a', text: 'Sensorineural hearing loss from oval-window injury' },
      { id: 'b', text: 'Tube malposition or kinking (and incomplete effusion evacuation)' },
      { id: 'c', text: 'Ossicular dislocation' },
      { id: 'd', text: 'Facial nerve injury' },
    ],
    correct: 'b',
    brief: 'Malposition/kinking — usually recognized and corrected on the table — is most common; SNHL and ossicular/facial injury are rare with correct quadrant technique.',
    detailed: 'Tube malposition or kinking is the usual intraoperative issue, prevented by a dedicated inserter, confirming lumen orientation before insertion, a perpendicular incision, and avoiding over-rotation. The second common pitfall is inadequate effusion clearance, leading to early post-op obstruction; gentle suction of the anterior sinus tympani/epitympanum where mucus pools helps. The catastrophic injuries listed (oval window/SNHL, ossicular, facial) are rare and largely avoided by staying in the anteroinferior quadrant with a perpendicular blade.',
    concepts: ['myringotomy', 'tubes'],
  },
  {
    id: 'q15',
    type: 'mcq',
    stem: 'On post-tube tympanometry, a patent functioning tube most characteristically produces:',
    options: [
      { id: 'a', text: 'A sharp Type A peak at 0 daPa' },
      { id: 'b', text: 'A flat (Type B) tracing with a LARGE ear-canal volume' },
      { id: 'c', text: 'A Type C tracing with markedly negative pressure' },
      { id: 'd', text: 'A flat (Type B) tracing with a SMALL/normal ear-canal volume' },
    ],
    correct: 'b',
    brief: 'A patent tube (or perforation) gives a flat trace with abnormally large equivalent volume, because the probe "sees" the middle ear and mastoid.',
    detailed: 'Distinguish the flat traces by volume: a flat Type B with large ear-canal volume means the probe is measuring the middle ear/mastoid through a patent tube or perforation — confirming the tube is open. A flat Type B with small/normal volume means an intact drum with effusion behind it (or an occluded tube). Type C (negative pressure) reflects ET dysfunction/retraction, and Type A is a normal aerated middle ear. So "tube working" is the large-volume flat curve — not Type A.',
    concepts: ['tympanometry', 'OME', 'physiology'],
  },
  {
    id: 'q16',
    type: 'mcq',
    stem: 'A toddler has stiff, thickened, immobile tympanograms (myringosclerosis). How should this shape counseling?',
    options: [
      { id: 'a', text: 'Tubes are contraindicated because the drum is calcified' },
      { id: 'b', text: 'Tubes are still indicated, but fibrosis may not fully reverse, so some residual conductive loss can persist' },
      { id: 'c', text: 'This guarantees an underlying ossicular discontinuity' },
      { id: 'd', text: 'No follow-up imaging is ever warranted' },
    ],
    correct: 'b',
    brief: 'Myringosclerosis reflects prior inflammation; tubes still help, but stiffened drums may not fully recover, so avoid over-promising complete resolution.',
    detailed: 'Stiff tymps indicate myringosclerosis/calcification of the fibrous layer from prior inflammation. Tubes remain indicated and usually improve function, but the remodeled drum may retain reduced compliance and a residual conductive component even after extrusion — so counsel cautiously. If hearing loss and stiff tymps persist after tubes, HRCT temporal bones is reasonable to exclude ossicular fixation or another structural anomaly. Young children remodel well overall, but the anatomic change is already underway.',
    concepts: ['tympanometry', 'OME', 'imaging'],
  },
  {
    id: 'q17',
    type: 'mcq',
    stem: 'In a child with stiff, immobile drums and disproportionate low-frequency conductive loss, which often-overlooked entity should prompt consideration of HRCT before tubes?',
    options: [
      { id: 'a', text: 'Superior semicircular canal dehiscence (SSCD)' },
      { id: 'b', text: 'Otitis externa' },
      { id: 'c', text: 'Tympanic membrane perforation' },
      { id: 'd', text: 'Cerumen impaction' },
    ],
    correct: 'a',
    brief: 'SSCD creates a third window producing a low-frequency air-bone gap and vestibular signs (Tullio, Hennebert) that can be misread as simple OME.',
    detailed: 'SSCD opens a "third window" in the labyrinth, lowering bone thresholds (sometimes negative) and creating a low-frequency conductive-appearing gap with intact acoustic reflexes — features that distinguish it from middle-ear conductive loss. Clues are autophony, sound-induced vertigo (Tullio), and pressure-induced dizziness (Hennebert sign). Most pediatric SSCD is asymptomatic, but a disproportionate low-frequency gap or any vestibular symptom warrants HRCT temporal bones rather than reflexively attributing the loss to effusion.',
    concepts: ['SSCD', 'imaging', 'middle-ear'],
  },
  {
    id: 'q18',
    type: 'mcq',
    stem: 'Post-tube otorrhea: the most accurate counseling for families is:',
    options: [
      { id: 'a', text: 'Any drainage means tube failure and immediate removal' },
      { id: 'b', text: 'Early drainage occurs in ~10–20% and usually resolves; topical ciprofloxacin drops are first-line if it persists/is infected' },
      { id: 'c', text: 'Otorrhea always requires systemic IV antibiotics' },
      { id: 'd', text: 'Drainage indicates the tube has migrated into the inner ear' },
    ],
    correct: 'b',
    brief: 'Some early drainage is common and expected (the tube is doing its job); persistent/infected otorrhea is treated with topical fluoroquinolone drops, water precautions help.',
    detailed: 'Acute otorrhea affects roughly 10–20% of tubes in the first 1–2 weeks, with chronic otorrhea in ~5–10%. Counsel that early drainage signals the tube is venting fluid rather than letting it pool. Topical ciprofloxacin (± dexamethasone) is first-line for persistent or infected drainage; systemic antibiotics are reserved for surrounding cellulitis or systemic illness. Reasonable water precautions reduce contamination. Most otorrhea settles by 4–8 weeks as the mucosa heals.',
    concepts: ['tube-complications', 'tubes'],
  },
  {
    id: 'q19',
    type: 'mcq',
    stem: 'A child returns with recurrent conductive loss and ear fullness after tube placement; the tube is in position. The most likely problem is:',
    options: [
      { id: 'a', text: 'Tube extrusion into the canal' },
      { id: 'b', text: 'Tube obstruction by dried mucus/debris/biofilm' },
      { id: 'c', text: 'Cholesteatoma formation' },
      { id: 'd', text: 'New-onset sensorineural loss' },
    ],
    correct: 'b',
    brief: 'A retained but blocked tube re-creates a conductive gap; antibiotic-steroid drops clear most, with in-office/OR cleaning if refractory.',
    detailed: 'Obstruction (5–15%, higher with thick mucoid effusion) blocks ventilation so conductive loss and fullness return despite the tube being in place — confirm with repeat audiometry/tympanometry (large-volume flat trace is lost). Management is ciprofloxacin-dexamethasone drops to soften debris and reduce inflammation; refractory cases need in-office or OR cleaning or reinsertion. Prevention: adequate intraoperative effusion clearance and early surveillance audiometry to catch obstruction before it causes functional loss.',
    concepts: ['tube-complications', 'tubes'],
  },
  {
    id: 'q20',
    type: 'mcq',
    stem: 'Regarding grommet extrusion and chronic OME (COME):',
    options: [
      { id: 'a', text: 'Grommets typically extrude at 6–12 months, and most drums heal without residual perforation (>95%)' },
      { id: 'b', text: 'Grommets are permanent and never extrude spontaneously' },
      { id: 'c', text: 'Extrusion before 3 months is expected and normal' },
      { id: 'd', text: 'Persistent perforation after extrusion occurs in the majority of children' },
    ],
    correct: 'a',
    brief: 'Grommets extrude around 6–12 months with >95% spontaneous closure; recurrent/persistent OME after extrusion defines COME and may warrant repeat tubes ± adenoidectomy.',
    detailed: 'Epithelial migration pushes grommets out at a median of 6–12 months (range ~3–18), and the great majority of drums heal completely (>95% closure). COME is effusion persisting >3 months despite appropriate management or recurring after extrusion; risk factors include Down syndrome, cleft palate, immunodeficiency, and cystic fibrosis. After a second set of tubes with ongoing symptoms, consider long-term (T-) tubes or adenoidectomy (especially if adenoid hypertrophy contributes to ET obstruction).',
    concepts: ['tube-complications', 'tubes', 'OME'],
  },
  // ─────────────── TONSILLECTOMY ───────────────
  {
    id: 'q21',
    type: 'mcq',
    stem: 'Using AHI thresholds, which child has moderate-to-severe OSA for which adenotonsillectomy is first-line?',
    options: [
      { id: 'a', text: 'AHI 1.5 with normal oxygen saturations' },
      { id: 'b', text: 'AHI 3 with mild snoring only' },
      { id: 'c', text: 'AHI 10.8' },
      { id: 'd', text: 'AHI 0.5' },
    ],
    correct: 'c',
    brief: 'Pediatric OSA: mild AHI 1–5, moderate 5–10, severe >10; adenotonsillectomy is first-line at AHI ≥5 (and improves/cures ~60–80%).',
    detailed: 'Pediatric severity bands (apneas + hypopneas per hour) are mild 1–5, moderate 5–10, severe >10 — note these are lower than adult cutoffs. Adenotonsillectomy is first-line for moderate-to-severe disease with significant improvement or resolution in roughly 60–80%. Mild OSA may be watched (frequent spontaneous resolution) unless there is recurrent infection or significant symptoms. AHI alone does not capture severity, however — a low AHI with profound desaturation (nadir <90%) or marked daytime symptoms can still justify surgery.',
    concepts: ['OSA', 'workup'],
  },
  {
    id: 'q22',
    type: 'mcq',
    stem: 'A colleague suggests watchful waiting for a 2-year-old with severe OSA (AHI ~11). The strongest argument to operate now is:',
    options: [
      { id: 'a', text: 'Tonsils never regress, so surgery is inevitable' },
      { id: 'b', text: 'Untreated severe OSA risks cor pulmonale, growth failure, and neurocognitive/behavioral harm during the at-risk window, and surgery resolves most cases within weeks' },
      { id: 'c', text: 'Surgery has zero hemorrhage or airway risk at this age' },
      { id: 'd', text: 'CPAP is contraindicated in all toddlers' },
    ],
    correct: 'b',
    brief: 'Adenotonsillar tissue does often regress with age, but severe OSA carries immediate cardiopulmonary, growth, and neurobehavioral risk that surgery rapidly reverses.',
    detailed: 'Pediatric OSA frequently improves as adenotonsillar tissue regresses after the 3–5 year peak, with spontaneous resolution rates around 10–30%/year — but severe disease is not something to gamble on. Untreated severe OSA threatens pulmonary hypertension/cor pulmonale, failure to thrive, and behavioral/cognitive impairment during the very years of rapid development. Adenotonsillectomy gives rapid symptomatic improvement (often within days) and cures or markedly improves ~80%, so the risk-benefit clearly favors surgery here despite the toddler\'s elevated perioperative risk.',
    concepts: ['OSA', 'counseling', 'regrowth'],
  },
  {
    id: 'q23',
    type: 'mcq',
    stem: 'Pre-operative workup for a young child with severe OSA most appropriately includes:',
    options: [
      { id: 'a', text: 'Routine carotid Doppler in every case' },
      { id: 'b', text: 'PSG/oximetry for severity, airway exam, a coagulation/VWD screen when history suggests, and echocardiography if cor pulmonale is suspected' },
      { id: 'c', text: 'Brain MRI for all children with snoring' },
      { id: 'd', text: 'No testing; proceed directly to surgery in all comers' },
    ],
    correct: 'b',
    brief: 'Quantify severity (PSG/oximetry), assess the airway, screen coagulation when indicated, and get an echo if signs of right-heart strain are present.',
    detailed: 'Tailored workup: polysomnography (or home oximetry if PSG is unavailable) quantifies AHI and the oxygen nadir, which drive monitoring level. Airway assessment (Mallampati, tonsil/adenoid size, retrognathia, hypotonia) flags possible difficult intubation. A coagulation screen / von Willebrand panel is reasonable when there is a personal or family bleeding history (VWD is common and underdiagnosed), though universal screening is not mandated. If severe OSA has produced signs of cor pulmonale (loud P2, hepatomegaly, RV strain), obtain an echocardiogram to guide anesthesia. A lateral neck film is optional adjunct for adenoid size.',
    concepts: ['OSA', 'workup'],
  },
  {
    id: 'q24',
    type: 'mcq',
    stem: 'On the Brodsky scale, tonsils that occupy roughly 50% of the oropharyngeal width between the pillars are graded:',
    options: [
      { id: 'a', text: '1+' },
      { id: 'b', text: '2+' },
      { id: 'c', text: '3+' },
      { id: 'd', text: '4+ ("kissing tonsils")' },
    ],
    correct: 'b',
    brief: 'Brodsky: 1+ in fossa, 2+ ~50% width, 3+ ~75%, 4+ midline-touching; size alone underestimates obstruction risk.',
    detailed: 'Brodsky grading: 1+ tips just past the pillars (~≤25%), 2+ ~50%, 3+ ~75%, 4+ touching in the midline. A 2+ tonsil is mild-to-moderate and low obstructive risk in isolation, but the picture changes with concurrent adenoid hypertrophy, retrognathia, hypotonia, or documented SDB. Size alone is an imperfect predictor — schemes like the Friedman staging add palate position and BMI — so tonsil grade must be integrated with the sleep/airway phenotype, not read in isolation.',
    concepts: ['brodsky', 'OSA', 'tonsil-anatomy'],
  },
  {
    id: 'q25',
    type: 'mcq',
    stem: 'In extracapsular (total) tonsillectomy, the correct dissection plane is between:',
    options: [
      { id: 'a', text: 'The tonsillar crypts and the medial epithelium' },
      { id: 'b', text: 'The tonsillar capsule and the superior pharyngeal constrictor muscle' },
      { id: 'c', text: 'The superior and middle pharyngeal constrictors' },
      { id: 'd', text: 'The palatoglossus and palatopharyngeus muscles' },
    ],
    correct: 'b',
    brief: 'Total tonsillectomy "peels" the tonsil off the superior constrictor along the capsule plane; seeing clean muscle fibers means you are correct, pulsatile deep tissue means too lateral/deep.',
    detailed: 'The extracapsular plane lies between the tonsillar capsule (pharyngeal-wall fascia) and the superior pharyngeal constrictor. Staying on the capsule "peels" the tonsil cleanly off muscle; the fossa is bounded by palatoglossus (anterior pillar) and palatopharyngeus (posterior pillar). If you see clear muscle fibers you are in plane; if you encounter deep red, pulsatile tissue you have strayed lateral/deep toward the constrictor and the internal carotid — stop and reorient. The same "find and respect the plane" principle recurs in intracapsular surgery and neck dissection.',
    concepts: ['extracapsular', 'tonsil-dissection', 'dissection-plane'],
  },
  {
    id: 'q26',
    type: 'mcq',
    stem: 'The single most important proactive hemostasis maneuver during extracapsular tonsillectomy is to:',
    options: [
      { id: 'a', text: 'Pack the nasopharynx tightly throughout the case' },
      { id: 'b', text: 'Control the tonsillar artery at the inferior pole before final delivery of the tonsil' },
      { id: 'c', text: 'Ligate the external carotid artery in the neck' },
      { id: 'd', text: 'Avoid all cautery to preserve the mucosa' },
    ],
    correct: 'b',
    brief: 'The inferior pole carries the dominant tonsillar artery; control it proactively rather than chasing brisk bleeding after the tonsil is off.',
    detailed: 'The inferior pole is the vascular pedicle (tonsillar branch of the facial artery) and the "point of no return" for bleeding control. Many surgeons cauterize or suture-ligate it before delivering the tonsil. If brisk inferior-pole bleeding starts, the safe sequence is pressure/pack, stay calm, get help, then cauterize or suture under direct vision — never blindly advance into a bleeding pole. Assess hemostasis fully on the first side before moving to the second; many post-op bleeds trace to a first side wrongly assumed secure.',
    concepts: ['tonsillar-artery', 'hemostasis', 'tonsil-dissection'],
  },
  {
    id: 'q27',
    type: 'mcq',
    stem: 'Which pair correctly matches an errant dissection direction with the structure it endangers?',
    options: [
      { id: 'a', text: 'Too superior/medial → internal carotid artery' },
      { id: 'b', text: 'Too lateral/deep → internal carotid artery; too far superior → soft-palate muscles (VPI)' },
      { id: 'c', text: 'Too lateral/deep → lingual nerve; too inferior → facial nerve' },
      { id: 'd', text: 'Any direction equally endangers the spinal accessory nerve' },
    ],
    correct: 'b',
    brief: 'Lateral/deep dissection threatens the ICA beyond the constrictor; over-superior dissection injures the levator/palatal muscles and risks velopharyngeal insufficiency.',
    detailed: 'The two cardinal spatial errors: straying lateral and deep past the superior constrictor approaches the internal carotid (rare but catastrophic — stay on the capsule), and extending too far superiorly toward the soft-palate insertion injures the palatal musculature, risking velopharyngeal insufficiency. Respect the inferior pole vascularly and never assume hemostasis. These are anatomy-driven decision points; rushing converts a controlled dissection into a hemorrhage- or VPI-prone one.',
    concepts: ['tonsil-dissection', 'carotid', 'VPI', 'dissection-plane'],
  },
  {
    id: 'q28',
    type: 'mcq',
    stem: 'The most common resident error during adenotonsillectomy — producing "failed" surgery with persistent obstruction — is:',
    options: [
      { id: 'a', text: 'Removing too much tonsil capsule' },
      { id: 'b', text: 'Incomplete adenoidectomy with residual tissue, often in the fossa of Rosenmüller' },
      { id: 'c', text: 'Over-aggressive inferior-pole cautery' },
      { id: 'd', text: 'Placing the patient in reverse Trendelenburg' },
    ],
    correct: 'b',
    brief: 'Residual adenoid (commonly in the fossa of Rosenmüller / choanal region) leaves persistent obstruction; ensure complete visualization and a clean nasopharyngeal roof.',
    detailed: 'Incomplete adenoidectomy — from inadequate neck extension, poor retraction, or limited nasopharyngeal visualization — leaves tissue (often laterally near the fossa of Rosenmüller or at the choanae) and persistent obstruction or recurrent symptoms. Prevent it by confirming a clean nasopharyngeal roof under direct/mirror/endoscopic view, palpating to confirm no remnant, and obtaining lateral neck imaging or endoscopy if symptoms persist. Avoid sweeping laterally into the eustachian-tube orifice (stenosis/scarring risk).',
    concepts: ['adenoidectomy', 'OSA'],
  },
  {
    id: 'q29',
    type: 'mcq',
    stem: 'For a toddler with severe OSA and large, congested glands, appropriate intraoperative modifications include:',
    options: [
      { id: 'a', text: 'Aggressive traction to speed delivery, since friable tissue tears easily' },
      { id: 'b', text: 'Gentler handling, earlier/proactive hemostasis, often electrocautery dissection, and IV dexamethasone to limit post-op airway edema' },
      { id: 'c', text: 'Avoiding all steroids to reduce bleeding risk' },
      { id: 'd', text: 'Deep extubation to minimize coughing' },
    ],
    correct: 'b',
    brief: 'Edematous OSA glands are friable and vascular — handle gently, control the pedicle early, and give intraoperative dexamethasone for post-op edema; awake (not deep) extubation.',
    detailed: 'Congested OSA tissue bleeds and tears readily, so reduce traction, identify and control the tonsillar artery proactively, favor electrocautery dissection, and keep larger-bore suction ready for brisk initial ooze. Intraoperative IV dexamethasone (~0.5 mg/kg) reduces post-op airway edema and PONV — the opposite of avoiding steroids. Because post-op airway edema is the dominant early risk in this group, extubation should be fully awake, not deep, with airway equipment at the bedside.',
    concepts: ['tonsil-dissection', 'OSA', 'airway-edema'],
  },
  {
    id: 'q30',
    type: 'mcq',
    stem: 'Recurrent throat infection now justifies tonsillectomy when episodes meet which (Paradise) threshold?',
    options: [
      { id: 'a', text: '≥3 episodes in a single year' },
      { id: 'b', text: '≥7 in 1 year, ≥5/year for 2 years, or ≥3/year for 3 years (adequately documented)' },
      { id: 'c', text: 'Any 2 episodes of strep pharyngitis' },
      { id: 'd', text: '≥10/year for 5 consecutive years' },
    ],
    correct: 'b',
    brief: 'Paradise criteria: 7 in one year, 5/year × 2 years, or 3/year × 3 years, with adequately documented qualifying episodes.',
    detailed: 'The Paradise criteria set the modern bar for infection-indicated tonsillectomy: 7 episodes in one year, 5 per year over two years, or 3 per year over three years, with each qualifying episode documented (fever, exudate, adenopathy, or positive culture). Recurrent pharyngitis is now a comparatively weak indication versus obstruction, reflecting modest benefit over watchful waiting in children who do not meet threshold.',
    concepts: ['counseling', 'tonsil-anatomy'],
  },
  {
    id: 'q31',
    type: 'mcq',
    stem: 'Which factors most justify planned overnight observation after adenotonsillectomy?',
    options: [
      { id: 'a', text: 'Age >12 years and mild OSA' },
      { id: 'b', text: 'Age <3 years, severe OSA (AHI >10), low pre-op oxygen nadir, or significant comorbidity' },
      { id: 'c', text: 'Intracapsular technique in a healthy 8-year-old' },
      { id: 'd', text: 'A normal preoperative polysomnogram' },
    ],
    correct: 'b',
    brief: 'Young age (<3), severe OSA, low O2 nadir, and major comorbidity drive overnight monitoring during the highest-risk first 24 hours.',
    detailed: 'Overnight admission is standard for age under ~3–4 years, severe OSA (AHI >10), preoperative oxygen nadir below ~85%, or significant cardiac/neurologic comorbidity — these predict post-op airway edema, hypoxia, and need for re-intervention, all clustering in the first 12–24 hours. Discharge criteria are stable saturations on room air, no stridor/distress, tolerating oral liquids, controlled pain, no bleeding signs, and a reliable caregiver. The same severe-OSA toddler is also the highest hemorrhage- and airway-risk patient on the list.',
    concepts: ['OSA', 'airway-edema'],
  },
  {
    id: 'q32',
    type: 'mcq',
    stem: 'For a 2-year-old with severe OSA, why is extracapsular (total) tonsillectomy preferred over intracapsular?',
    options: [
      { id: 'a', text: 'Intracapsular has a higher hemorrhage rate' },
      { id: 'b', text: 'Extracapsular maximizes airway benefit and minimizes regrowth/recurrence, an acceptable trade for its slightly higher bleeding risk in severe disease' },
      { id: 'c', text: 'Intracapsular cannot be performed under 5 years of age' },
      { id: 'd', text: 'Extracapsular eliminates all post-op pain' },
    ],
    correct: 'b',
    brief: 'Total tonsillectomy gives complete obstruction relief with negligible regrowth; intracapsular\'s lower-bleeding advantage is outweighed when OSA is severe.',
    detailed: 'Technique selection trades bleeding risk against completeness. Extracapsular removes all lymphoid tissue and capsule for maximal, durable airway relief (minimal regrowth) at a higher hemorrhage rate (~1% primary, ~2–4% secondary). Intracapsular leaves a capsular rim, halving hemorrhage risk and reducing pain, but ~5–15% regrow and may need revision. For severe OSA the definitive airway benefit wins, with age-appropriate monitoring covering the bleeding risk. Intracapsular shines for mild OSA or high bleeding risk — not severe obstruction.',
    concepts: ['extracapsular', 'intracapsular', 'OSA', 'regrowth'],
  },
  // ─────────────── INTRACAPSULAR ───────────────
  {
    id: 'q33',
    type: 'mcq',
    stem: 'The principle that makes intracapsular (partial) tonsillectomy lower-bleeding than extracapsular is:',
    options: [
      { id: 'a', text: 'It cauterizes the external carotid artery proximally' },
      { id: 'b', text: 'It removes the lymphoid core while leaving the capsule intact, so the larger tonsillar artery stays embedded and only small capsular vessels are exposed' },
      { id: 'c', text: 'It is performed without any energy device' },
      { id: 'd', text: 'It exposes the superior constrictor for direct suture closure' },
    ],
    correct: 'b',
    brief: 'Leaving the capsule keeps the major (inferior-pole) tonsillar artery covered and exposes only small, easily controlled capsular vessels — and spares bare muscle from scab-separation bleeds.',
    detailed: 'Intracapsular surgery ablates/removes the lymphoid core within the capsule, which remains as a protective lining over the superior constrictor. The dominant tonsillar artery stays embedded rather than transected and exposed, so bleeding sources are small capsular vessels (minor ooze). The intact capsule also acts as a healing scaffold, reducing the secondary (scab-separation) bleeds that arise when extracapsular surgery leaves bare muscle with eroding vessels. Net effect: primary hemorrhage ~0.3–0.5% versus ~1% for total.',
    concepts: ['intracapsular', 'capsule', 'hemostasis'],
  },
  {
    id: 'q34',
    type: 'mcq',
    stem: 'After intracapsular tonsillectomy, what is the expected residual burden and regrowth risk?',
    options: [
      { id: 'a', text: 'Zero residual tissue; regrowth is impossible' },
      { id: 'b', text: '~20–40% residual volume; ~5–15% regrow enough to need revision, highest in the youngest children' },
      { id: 'c', text: '~80% residual volume, defeating any airway benefit' },
      { id: 'd', text: 'Regrowth only occurs after age 10' },
    ],
    correct: 'b',
    brief: 'A capsular rim (~20–40% volume) remains; ~5–15% regrow significantly, with highest risk during the 3–5 year lymphoid-growth peak.',
    detailed: 'Intracapsular leaves roughly 20–40% of the original volume as a capsular remnant — typically reducing a 3+ tonsil to ~1–1.5+. Regrowth can begin at 3–6 months and become clinically significant over 6–18 months, with overall revision rates ~5–15%; risk is highest in the youngest children (peak lymphoid growth 3–5 years), with severe pre-op hypertrophy, or when an adenoid-dominant component is left untreated. Counsel families that regrowth, if it happens, is usually sub-original and amenable to a simpler completion procedure.',
    concepts: ['intracapsular', 'regrowth', 'capsule'],
  },
  {
    id: 'q35',
    type: 'mcq',
    stem: 'Which statement about intracapsular tonsillectomy technique (coblation, microdebrider, or partial blunt dissection) is correct?',
    options: [
      { id: 'a', text: 'All three aim to remove the capsule along with the lymphoid core' },
      { id: 'b', text: 'All three share the goal of preserving the capsule; coblation uses a lower-temperature radiofrequency plasma field than monopolar cautery' },
      { id: 'c', text: 'Coblation runs hotter than monopolar electrocautery' },
      { id: 'd', text: 'Microdebrider technique requires ligating the tonsillar artery in every case' },
    ],
    correct: 'b',
    brief: 'The shared principle is capsule preservation; coblation ablates tissue with a relatively low-temperature bipolar radiofrequency plasma, reducing collateral thermal injury.',
    detailed: 'Whatever the tool, the defining feature of intracapsular surgery is preserving the capsule — removing the capsule converts it to a (near-)total extracapsular procedure and forfeits the bleeding advantage. Coblation generates a bipolar radiofrequency plasma field at substantially lower temperatures than monopolar electrocautery (which reaches several hundred degrees), so it vaporizes tissue with simultaneous hemostasis and less charring/collateral injury. Microdebrider and partial blunt dissection are alternatives; none requires routine tonsillar-artery ligation if the capsule is respected.',
    concepts: ['intracapsular', 'capsule', 'hemostasis'],
  },
  {
    id: 'q36',
    type: 'mcq',
    stem: 'During intracapsular dissection, you recognize you have reached the correct depth when:',
    options: [
      { id: 'a', text: 'You see dark red, soft lymphoid tissue with brisk arterial bleeding' },
      { id: 'b', text: 'You see white, glistening, firmer fibrous capsule with only small-vessel ooze' },
      { id: 'c', text: 'You expose the superior constrictor muscle fibers' },
      { id: 'd', text: 'The dissector passes without any resistance at all' },
    ],
    correct: 'b',
    brief: 'The capsule is a firm, white, glistening fascial boundary with minor ooze; brisk arterial bleeding or exposed muscle means you have gone too deep.',
    detailed: 'Correct intracapsular depth is the firm, white, glistening capsule (pharyngeal-wall fascia), distinct from the softer dark lymphoid core, felt as increased fibrous resistance and showing only small capsular ooze. The most common error is dissecting too deep/medially, breaking through the capsule into the superior constrictor — this converts the case to a near-total resection, exposes larger vessels, and forfeits the hemostasis advantage. Brisk arterial bleeding signals you have breached the plane: stop, reassess, get help.',
    concepts: ['intracapsular', 'capsule', 'dissection-plane'],
  },
  {
    id: 'q37',
    type: 'mcq',
    stem: 'When counseling a family choosing between intracapsular and extracapsular tonsillectomy, the honest trade-off is:',
    options: [
      { id: 'a', text: 'Intracapsular fully removes the tonsils with no regrowth and less bleeding' },
      { id: 'b', text: 'Intracapsular means less bleeding and pain but a small chance (~10%) of regrowth needing a second procedure; extracapsular is definitive but bleeds slightly more' },
      { id: 'c', text: 'Extracapsular has lower bleeding risk than intracapsular' },
      { id: 'd', text: 'The two techniques have identical outcomes in every respect' },
    ],
    correct: 'b',
    brief: 'Intracapsular: lower bleeding/pain, ~10% regrowth risk; extracapsular: definitive with negligible regrowth but slightly higher hemorrhage — match to severity and bleeding risk.',
    detailed: 'Frame it plainly: intracapsular preserves the outer lining, cutting primary hemorrhage to ~0.3–0.5% and easing recovery, at the cost of ~10% regrowth (usually sub-original, fixable with a simpler revision). Extracapsular removes everything for a definitive result with negligible regrowth but ~1% primary / 2–4% secondary bleeding. Recommend intracapsular for mild OSA, younger children, or elevated bleeding risk; reserve extracapsular for moderate-to-severe OSA where complete relief matters most.',
    concepts: ['intracapsular', 'extracapsular', 'counseling'],
  },
  // ─────────────── NECK NODE ───────────────
  {
    id: 'q38',
    type: 'mcq',
    stem: 'Cervical Level II is subdivided into IIa and IIb by which structure, and which nerve is the principal one at risk?',
    options: [
      { id: 'a', text: 'Divided by the internal jugular vein; the vagus nerve is at risk' },
      { id: 'b', text: 'Divided by the spinal accessory nerve (CN XI); CN XI itself is the principal nerve at risk' },
      { id: 'c', text: 'Divided by the omohyoid; the hypoglossal nerve is at risk' },
      { id: 'd', text: 'Divided by the carotid bifurcation; the facial nerve is at risk' },
    ],
    correct: 'b',
    brief: 'The spinal accessory nerve separates IIa (anterior) from IIb (posterior); CN XI is the key structure to identify and protect, with IIb dissection riskier.',
    detailed: 'Level II (upper jugular) runs from skull base to the hyoid, bounded laterally by the SCM and medially toward the carotid/hyoglossus, with the posterior belly of digastric superiorly. The spinal accessory nerve (CN XI) divides IIa (anteromedial to the nerve) from IIb (posterolateral, behind the nerve) — IIb sits in the nerve\'s descending path and is higher-risk. Other structures in/near the field: internal jugular vein (lateral, drains the chain, with the facial vein entering superiorly), vagus within the carotid sheath, common/internal carotid medially, and hypoglossal (CN XII) crossing anterior to the ICA. Identify CN XI early before nodal dissection.',
    concepts: ['nodal-anatomy', 'spinal-accessory', 'carotid', 'cranial-nerves'],
  },
  {
    id: 'q39',
    type: 'mcq',
    stem: 'A young child has chronic, calcified cervical nodes. Which infectious cause is most characteristic?',
    options: [
      { id: 'a', text: 'Acute Group A streptococcal lymphadenitis' },
      { id: 'b', text: 'Nontuberculous (atypical) mycobacteria, with tuberculosis also classically calcifying' },
      { id: 'c', text: 'Epstein–Barr virus mononucleosis' },
      { id: 'd', text: 'Acute Staphylococcus aureus suppuration' },
    ],
    correct: 'b',
    brief: 'Chronic, calcified, often painless nodes in young children suggest nontuberculous mycobacteria (or TB); acute suppurative causes are staph/strep.',
    detailed: 'Calcification implies a chronic or healed granulomatous process. In children under ~5, nontuberculous mycobacteria (MAC, M. marinum) are the classic indolent cause — often a violaceous, minimally tender node that can fistulize; TB nodes characteristically calcify as well. Acute, tender, suppurative adenitis points to S. aureus or Group A strep, and EBV/CMV give reactive, non-calcified adenopathy. Other granulomatous/fungal causes (sarcoid, coccidioidomycosis, histoplasmosis) and treated lymphoma round out the calcified-node differential.',
    concepts: ['lymphadenitis', 'imaging'],
  },
  {
    id: 'q40',
    type: 'mcq',
    stem: 'For a 16-year-old with a recurrent 1–1.5 cm calcified Level II node, which feature is reassuring, and what is the role of fine-needle aspiration (FNA)?',
    options: [
      { id: 'a', text: 'Rapid growth is reassuring; FNA is mandatory before any excision' },
      { id: 'b', text: 'Calcification, small size, mobility, and recurrence favor a benign process; FNA is low-yield here, so excisional biopsy is both diagnostic and therapeutic' },
      { id: 'c', text: 'Matted, fixed nodes are reassuring; FNA replaces excision' },
      { id: 'd', text: 'Constitutional symptoms are reassuring; observation alone suffices' },
    ],
    correct: 'b',
    brief: 'Calcified, small, mobile, recurrent nodes read as benign; FNA adds little for presumed benign recurrent adenitis, so excision provides both diagnosis and cure.',
    detailed: 'Reassuring features are calcification, size in the 1–1.5 cm range, mobility, and a recurrent rather than progressive course. Red flags (absent here) are rapid enlargement, matted/fixed nodes, constitutional symptoms (fever, weight loss, night sweats), multi-level involvement, and very young age with a firm painless node. FNA is most useful when malignancy suspicion is meaningful and would change management; for presumed benign recurrent adenitis it is low-yield and may miss the target, so proceeding to excisional biopsy gives definitive pathology and removes the recurrent focus in one step.',
    concepts: ['node-malignancy', 'workup', 'lymphadenitis'],
  },
  {
    id: 'q41',
    type: 'mcq',
    stem: 'Injury to the spinal accessory nerve during Level IIb dissection produces:',
    options: [
      { id: 'a', text: 'Tongue deviation and hemiatrophy' },
      { id: 'b', text: 'Trapezius denervation: shoulder droop, impaired arm abduction above 90°, and lateral scapular winging' },
      { id: 'c', text: 'Hoarseness and aspiration' },
      { id: 'd', text: 'Miosis, ptosis, and anhidrosis' },
    ],
    correct: 'b',
    brief: 'CN XI denervates trapezius; injury causes shoulder drop, weak abduction past 90°, and lateral scapular winging, not tongue or voice changes.',
    detailed: 'The spinal accessory nerve supplies the trapezius (and SCM); injury gives shoulder droop, pain, weakness abducting the arm above 90°, and lateral winging of the scapula. Protect it by exposing the posterior SCM border and identifying the nerve (emerging near the junction of the upper and middle third) before nodal dissection, then using blunt instruments to separate the node, ligating small feeders individually rather than avulsing the node. If a node is densely adherent to CN XI, partial excision is safer than risking permanent palsy — and should be documented. Tongue deviation = CN XII, hoarseness = CN X/vagus, the Horner triad = sympathetic chain.',
    concepts: ['spinal-accessory', 'node-dissection', 'cranial-nerves', 'dissection-plane'],
  },
  {
    id: 'q42',
    type: 'mcq',
    stem: 'If brisk bleeding is encountered from the internal jugular vein during node excision, the correct principle is:',
    options: [
      { id: 'a', text: 'Immediately attempt primary venous repair single-handed' },
      { id: 'b', text: 'Direct pressure first; the IJV can be safely ligated unilaterally if needed, whereas a major carotid injury demands pressure plus vascular-surgery backup' },
      { id: 'c', text: 'Ligate the common carotid to control the field' },
      { id: 'd', text: 'Use blind monopolar cautery deep in the wound' },
    ],
    correct: 'b',
    brief: 'Control with pressure; unilateral IJV ligation is tolerated via collateral drainage, but carotid injury is a call-for-help/maintain-pressure emergency, not a solo repair.',
    detailed: 'For IJV bleeding: direct pressure, identify the source, then control tributaries (e.g., facial vein) or, if the vein is transected, ligate proximally and distally — unilateral IJV ligation is tolerated through the contralateral IJV, external jugular, and vertebral collaterals (bilateral ligation, by contrast, risks raised ICP/cerebral edema). Prefer bipolar near nerves/vessels over monopolar. A main carotid injury is beyond a junior solo repair: keep your hand on it (maintain pressure), call anesthesia and vascular surgery immediately, and buy time.',
    concepts: ['carotid', 'node-dissection', 'hemostasis'],
  },
  {
    id: 'q43',
    type: 'mcq',
    stem: 'Why is Horner syndrome an unlikely complication of a Level II node excision?',
    options: [
      { id: 'a', text: 'The sympathetic chain is not located in the neck at all' },
      { id: 'b', text: 'The cervical sympathetic chain lies deep along the carotid sheath lower in the neck; Horner implies dissection strayed too deep/low, outside Level IIa–IIb' },
      { id: 'c', text: 'Horner only follows spinal accessory nerve injury' },
      { id: 'd', text: 'Horner requires bilateral nodal dissection' },
    ],
    correct: 'b',
    brief: 'Staying within Level IIa–IIb keeps you away from the deep cervical sympathetic chain; a post-op Horner suggests deeper/lower dissection than indicated.',
    detailed: 'Horner syndrome (ipsilateral miosis, ptosis, anhidrosis) follows injury to the cervical sympathetic chain, which runs deep along the carotid sheath, lower in the neck than the Level II nodal field. A correctly bounded Level IIa–IIb excision should not reach it, so a new Horner sign post-op is a warning that dissection extended too deep or too low (toward the carotid sheath/lower levels), with concern for deeper injury. Knowing the boundaries of the indicated dissection — here a single-node excision, not a modified radical neck dissection — is itself the safeguard.',
    concepts: ['horner', 'node-dissection', 'carotid'],
  },
  {
    id: 'q44',
    type: 'mcq',
    stem: 'Routine post-operative surveillance after a Level II node excision centers on:',
    options: [
      { id: 'a', text: 'Immediate post-op MRI for all patients' },
      { id: 'b', text: 'Serial neurologic checks (shoulder/trapezius, tongue, voice, swallow), wound/hematoma assessment, and pathology review, with most nerve deficits resolving by ~3 months' },
      { id: 'c', text: 'Lifelong annual CT regardless of pathology' },
      { id: 'd', text: 'No follow-up once the patient leaves recovery' },
    ],
    correct: 'b',
    brief: 'Watch for bleeding/hematoma and nerve injury (CN XI, XII, X), confirm pathology, and reassess at 1–2 weeks and ~3 months; persistent deficits at 3 months suggest permanent injury.',
    detailed: 'Surveillance is clinical: assess shoulder elevation/abduction (CN XI), tongue protrusion (CN XII), voice and swallow (CN X), and the wound for hematoma — a neck hematoma can threaten the airway. Remove a drain at 24–48 h if placed, recheck the neuro exam at 1–2 weeks (delayed deficits from edema/hematoma), and review pathology to confirm the etiology. Most nerve injuries from edema/traction recover within 3 months; deficits persisting at 3 months suggest a permanent lesion. Routine imaging is reserved for suspected complication or recurrence.',
    concepts: ['node-dissection', 'workup', 'cranial-nerves'],
  },
  // ─────────────── COMPLICATIONS ───────────────
  {
    id: 'q45',
    type: 'mcq',
    stem: 'Post-tonsillectomy hemorrhage: which statement about timing and the "rule of 5s" is correct?',
    options: [
      { id: 'a', text: 'Primary hemorrhage occurs after 24 hours; secondary within the first 6 hours' },
      { id: 'b', text: 'Primary occurs within 24 hours (usually 0–6 h); secondary occurs after 24 hours, peaking around post-op day 5–7 with scab separation' },
      { id: 'c', text: 'Both primary and secondary peak on the day of surgery' },
      { id: 'd', text: 'Secondary hemorrhage is more common than dental caries and occurs in 50% of children' },
    ],
    correct: 'b',
    brief: 'Primary = within 24 h (often 0–6 h); secondary = after 24 h, peaking ~day 5–7 as the eschar separates; overall bleeding risk is a few percent, higher under age 3.',
    detailed: 'Primary hemorrhage (within 24 hours, usually 0–6 h) is the most dangerous because of aspiration/airway risk — the explicit reason for overnight admission in high-risk children. Secondary hemorrhage occurs after 24 hours and peaks around day 5–7 when the fibrin eschar separates, classically triggered by hot fluids, vigorous coughing, or infection. Rough incidences: primary ~0.5–1%, secondary ~1–4%. Risk rises with coagulopathy (e.g., von Willebrand disease), thrombocytopenia, young age (<3), difficult/large-gland dissection, and post-op infection.',
    concepts: ['hemorrhage', 'counseling'],
  },
  {
    id: 'q46',
    type: 'mcq',
    stem: 'A child presents with brisk post-tonsillectomy bleeding. Initial management and the threshold for returning to the OR are:',
    options: [
      { id: 'a', text: 'Lay the child flat, sedate heavily, and observe all bleeds at the bedside' },
      { id: 'b', text: 'NPO, sit upright/forward-leaning, IV access with type-and-cross/labs, gentle suction; return to OR for active/pulsatile bleeding, instability, or airway compromise' },
      { id: 'c', text: 'Aggressively suction and probe the fossae at the bedside to find the vessel' },
      { id: 'd', text: 'Give oral fluids immediately to flush the clot' },
    ],
    correct: 'b',
    brief: 'Stabilize NPO and upright with IV access and labs, suction gently; take to the OR for active/pulsatile bleeding, hemodynamic instability, or any airway involvement.',
    detailed: 'Initial steps: NPO, position upright and forward-leaning to protect the airway, secure large-bore IV access with CBC/coags/type-and-cross, and suction gently (aggressive suction dislodges protective clot). Avoid definitive bedside management — visualization and control are poor and aspiration risk is high. Return to the OR for active or pulsatile bleeding, hemodynamic instability, or airway compromise; minor blood-tinged saliva in a stable, closely monitored child may be observed with cool liquids and head-up positioning. Anticipate a difficult airway (blood, swelling) on re-exploration.',
    concepts: ['hemorrhage', 'airway-edema'],
  },
  {
    id: 'q47',
    type: 'mcq',
    stem: 'Velopharyngeal insufficiency after adenotonsillectomy: which is most accurate?',
    options: [
      { id: 'a', text: 'It is common (>10%) and usually permanent' },
      { id: 'b', text: 'It is rare (<1%); transient post-op VPI from edema usually resolves in weeks, and persistent VPI should prompt evaluation for an occult cause such as 22q11 deletion' },
      { id: 'c', text: 'It is caused by spinal accessory nerve injury' },
      { id: 'd', text: 'It always requires immediate surgical pharyngoplasty' },
    ],
    correct: 'b',
    brief: 'Persistent VPI is <1%; transient edema-related VPI resolves over weeks, and lasting VPI suggests occult neuromuscular pathology (e.g., 22q11/velocardiofacial).',
    detailed: 'VPI is failure of the soft palate to seal against the posterior pharyngeal wall, giving hypernasal speech and nasal regurgitation. The relevant motor supply is the vagus (CN X) via levator veli palatini and the pharyngeal plexus — not the spinal accessory nerve. Post-T&A persistent VPI is <1%; acute VPI from edema usually clears within 1–3 weeks. VPI lasting beyond ~3 months warrants nasendoscopy/videofluoroscopy and a search for an underlying cause such as 22q11 deletion (velocardiofacial syndrome) or a submucous cleft. Prevention: avoid deep superior dissection into the palatal musculature and over-superior adenoidectomy.',
    concepts: ['VPI', 'cranial-nerves'],
  },
  {
    id: 'q48',
    type: 'mcq',
    stem: 'Post-tonsillectomy dysphagia in a toddler is best managed by:',
    options: [
      { id: 'a', text: 'Encouraging hot fluids and hard/crunchy foods to toughen the fossae' },
      { id: 'b', text: 'Scheduled analgesia, hydration, and graded soft/cool diet; treat inability to swallow saliva or signs of aspiration as red flags' },
      { id: 'c', text: 'Routine opioids around the clock as first-line' },
      { id: 'd', text: 'Strict NPO for two weeks' },
    ],
    correct: 'b',
    brief: 'Pain control and hydration with a cool soft diet; escalate only for red flags (cannot swallow saliva, drooling, respiratory signs) suggesting bleeding/infection.',
    detailed: 'Some dysphagia is near-universal post-T&A, worst at 24–72 hours and improving over 1–2 weeks. Management is scheduled acetaminophen ± ibuprofen (NSAID bleeding risk is debated but evidence largely does not show a clinically meaningful increase), maintaining hydration (dehydration is a leading readmission cause), and a graded cool/soft diet while avoiding hot, spicy, and hard/crunchy foods. Red-flag dysphagia — inability to swallow saliva, excessive drooling, respiratory distress, or aspiration signs — should trigger evaluation for hemorrhage or infection rather than reassurance.',
    concepts: ['dysphagia', 'counseling'],
  },
  {
    id: 'q49',
    type: 'mcq',
    stem: 'Across a pediatric OR list, which profile carries the HIGHEST post-operative hemorrhage risk?',
    options: [
      { id: 'a', text: 'A 16-year-old undergoing a single Level II node excision' },
      { id: 'b', text: 'A 2-year-old with severe OSA undergoing extracapsular adenotonsillectomy' },
      { id: 'c', text: 'A 19-month-old undergoing bilateral tube placement' },
      { id: 'd', text: 'A 7-year-old undergoing intracapsular tonsillectomy' },
    ],
    correct: 'b',
    brief: 'Toddler age + severe OSA (large, vascular glands) + extracapsular technique stack the highest hemorrhage risk; tubes carry essentially none.',
    detailed: 'Risk stacks multiplicatively: young age (<3) raises bleeding risk, severe OSA means large, vascular, friable glands with more disrupted tissue planes, and extracapsular technique exposes the tonsillar artery and bare muscle (~1% primary / 2–4% secondary). That combination tops the list and justifies overnight observation. Intracapsular technique and older age lower risk; myringotomy/tubes have negligible hemorrhage risk (small TM incision); and a single node excision in an adolescent is comparatively low risk. This same toddler is also the highest airway-edema risk.',
    concepts: ['hemorrhage', 'OSA'],
  },
  // ─────────────── INTEGRATION / CASES ───────────────
  {
    id: 'q50',
    type: 'mcq',
    stem: 'A 19-month-old with OME (SAT ~55 dB) and speech delay is scheduled for tubes. Regarding speech-language pathology (SLP):',
    options: [
      { id: 'a', text: 'Refer to SLP only if language has not normalized 6 months after surgery' },
      { id: 'b', text: 'Refer to SLP before surgery for baseline assessment and concurrent therapy; expect immediate hearing gain but gradual language catch-up over months' },
      { id: 'c', text: 'No SLP is needed because tubes restore language directly' },
      { id: 'd', text: 'Delay all therapy until after tube extrusion' },
    ],
    correct: 'b',
    brief: 'Refer to SLP before surgery (baseline + concurrent therapy); hearing improves within days–weeks, but language catch-up follows a slower months-long trajectory.',
    detailed: 'SLP involvement belongs before surgery: establish a baseline with an age-appropriate tool, identify which domains are affected, screen for co-occurring developmental delay, and begin concurrent therapy with caregiver coaching rather than waiting on post-op gains. Hearing improves within days to a few weeks as pressure equalizes and fluid resorbs, but receptive/expressive language re-accelerates over 3–6 months and may take 12–24 months to normalize, given the input missed during the 12–24 month vocabulary surge. A 3-month audiogram showing the gap closed to <20 dB confirms the conductive loss was the bottleneck and validates intensifying SLP.',
    concepts: ['cases', 'OME', 'counseling'],
  },
  {
    id: 'q51',
    type: 'mcq',
    stem: 'A 2-year-old with severe OSA (AHI ~11) is having adenotonsillectomy. Which anesthetic/airway plan is most appropriate?',
    options: [
      { id: 'a', text: 'Heavy premedication, opioid-rich maintenance, and deep extubation' },
      { id: 'b', text: 'Gentle inhalational induction preserving spontaneous ventilation, opioid-sparing maintenance, intraoperative dexamethasone, and fully awake extubation with airway equipment ready' },
      { id: 'c', text: 'Avoid steroids and extubate deep to reduce coughing' },
      { id: 'd', text: 'Mandatory tracheostomy before the procedure' },
    ],
    correct: 'b',
    brief: 'Severe-OSA toddlers need spontaneous-ventilation induction, opioid-sparing technique (OSA heightens opioid sensitivity), dexamethasone for edema, and awake extubation.',
    detailed: 'Children with severe OSA are sensitive to opioids and prone to post-op airway collapse, so avoid heavy premedication, favor a gentle inhalational induction that preserves spontaneous ventilation, anticipate a potentially difficult airway, and minimize opioids (use acetaminophen/regional adjuncts). Give intraoperative dexamethasone to blunt airway edema, and extubate only when fully awake with the gag intact — not deep — keeping reintubation equipment and nebulized epinephrine at the bedside. Continuous pulse oximetry/capnography and semi-upright positioning cover the high-risk first 24 hours, the rationale for overnight admission.',
    concepts: ['cases', 'anesthesia', 'airway-edema', 'OSA'],
  },
  {
    id: 'q52',
    type: 'mcq',
    stem: 'A 5-year-old with a seizure disorder is undergoing adenotonsillectomy. Which anesthetic plan best fits?',
    options: [
      { id: 'a', text: 'Use methohexital for induction and continue ketamine maintenance' },
      { id: 'b', text: 'Continue all antiepileptics perioperatively, favor propofol/volatile agents, and avoid seizure-threshold-lowering drugs like methohexital and ketamine' },
      { id: 'c', text: 'Hold all antiepileptics on the morning of surgery' },
      { id: 'd', text: 'Avoid propofol because it provokes seizures' },
    ],
    correct: 'b',
    brief: 'Keep AEDs running, choose propofol/volatile agents (propofol is anticonvulsant), and avoid methohexital and ketamine, which lower the seizure threshold.',
    detailed: 'Maintain seizure control through the perioperative period: continue all antiepileptic drugs (abrupt withdrawal plus surgical stress/fever invites breakthrough seizures) and plan IV dosing if the child will be NPO. Favor propofol (intrinsically anticonvulsant) and volatile agents/nitrous oxide; avoid methohexital and ketamine, which lower the seizure threshold. Aggressively manage post-op pain, fever, and hypoxia, since all are seizure triggers, and keep seizure precautions at the bedside. Coordinate with neurology on agent choices and post-op coverage.',
    concepts: ['cases', 'anesthesia', 'seizure'],
  },
  {
    id: 'q53',
    type: 'mcq',
    stem: 'The same 5-year-old has bilateral cochlear implants. Which perioperative consideration is correct?',
    options: [
      { id: 'a', text: 'Place ECG/grounding pads and apply monopolar cautery freely over the mastoid processors' },
      { id: 'b', text: 'Avoid cautery, suction, retractors, and adhesive pads over the processor/mastoid sites, prefer bipolar, and coordinate device checks with the CI team' },
      { id: 'c', text: 'Cochlear implants preclude general anesthesia entirely' },
      { id: 'd', text: 'The implants increase post-tonsillectomy bleeding risk' },
    ],
    correct: 'b',
    brief: 'Keep instruments/pads/monopolar cautery away from the mastoid devices, prefer bipolar, and loop in the CI team; the implants do not affect bleeding but complicate emergent reintubation positioning.',
    detailed: 'Protect the devices: avoid suction, retractors, adhesive ECG pads, and especially monopolar electrocautery over the behind-the-ear processors/mastoid (risk of electrode damage or device malfunction); prefer bipolar if cautery is needed near them and position pads on the chest away from the implants. Inform the CI team of the surgery so they can test/reprogram afterward. The implants do not change tonsillectomy bleeding risk, but they do complicate head positioning and emergent reintubation if airway edema develops — relevant given the child\'s coexisting SDB and seizure history.',
    concepts: ['cases', 'cochlear-implant', 'anesthesia'],
  },
  {
    id: 'q54',
    type: 'mcq',
    stem: 'A 6-year-old with allergic rhinitis is scheduled for adenotonsillectomy for SDB. The most useful pre-operative optimization is:',
    options: [
      { id: 'a', text: 'Stop all nasal steroids to avoid masking infection' },
      { id: 'b', text: 'Optimize allergic control (intranasal steroids 2–4 weeks pre-op ± antihistamine/montelukast), assess for asthma, and plan humidification/hydration for the post-op airway' },
      { id: 'c', text: 'Use histamine-releasing neuromuscular blockers to test airway reactivity' },
      { id: 'd', text: 'Avoid all anti-inflammatory therapy perioperatively' },
    ],
    correct: 'b',
    brief: 'Treat the allergic inflammation before surgery (intranasal steroids ± antihistamine/leukotriene blocker), screen for asthma, and plan post-op humidification — allergic airways edematize and react more.',
    detailed: 'Allergic rhinitis raises airway reactivity, mucus production, and post-op edema and may heighten pain perception and slow healing. Optimize ahead of time: start/continue intranasal steroids 2–4 weeks pre-op, add an antihistamine and consider montelukast (especially with allergic asthma), and screen for/optimize asthma to avoid intra- or post-op bronchospasm. Plan aggressive humidification and hydration to thin secretions, continue nasal steroids post-op, and for paralysis prefer rocuronium/vecuronium over histamine-releasing agents (atracurium/cisatracurium). Expect a slightly higher discharge threshold for airway watchfulness.',
    concepts: ['cases', 'anesthesia', 'airway-edema'],
  },
];

window.OCC_tatubes = { meta, DOMAINS, CONCEPTS, ITEMS };
